[WIP][mdex-integration][feat] implement mdex add base token only strat.
alpaca-finance/bsc-alpaca-contract pull request #121
Opened 2021-08-31 04:19 UTC by blackalpacaa

## Description

## Why?

## ChangeLogs:

### Link to story (if available)

2021-08-31 08:04 UTC, alpanaca commented on contracts/6/protocol/strategies/mdexswap-restricted/MdexRestrictedStrategyAddBaseTokenOnly.sol
> +  /// @notice This function is written base on fee=988, feeDenom=1000
Need to update this to reflex the actual implementation

2021-09-03 12:47 UTC, jr-alpaca commented on contracts/6/protocol/strategies/mdexswap-restricted/MdexRestrictedStrategyAddBaseTokenOnly.sol
> +  address public mdx;
move this one to below router at line 35.

2021-09-03 12:48 UTC, jr-alpaca commented on contracts/6/protocol/strategies/mdexswap-restricted/MdexRestrictedStrategyAddBaseTokenOnly.sol
> +  function initialize(IMdexRouter _router, address _mdx) external initializer {
/// @param _mdx The address of mdex token.

2021-09-03 12:52 UTC, jr-alpaca commented on test/Mdex_Restricted_StrategyAddBaseTokenOnly.test.ts
> +        const fee = await factory.getPairFees(lp.address)
remove this line since this variable is not used.

2021-09-06 05:18 UTC, spicysquid168 requested changes

2021-09-06 05:18 UTC, spicysquid168 commented on contracts/6/protocol/strategies/mdexswap-restricted/MdexRestrictedStrategyAddBaseTokenOnly.sol
> +    // get trading fee of each pairs
2. Get trading fee of the pair from Mdex

2021-09-06 05:18 UTC, spicysquid168 commented on contracts/6/protocol/strategies/mdexswap-restricted/MdexRestrictedStrategyAddBaseTokenOnly.sol
> +    // 2. Approve router to do their stuffs
Sequence

2021-09-06 05:18 UTC, spicysquid168 commented on test/Mdex_Restricted_StrategyAddBaseTokenOnly.test.ts
> +        // actualLpAmount = 0.015419263215025115
Why there is quite a diff between actualLpAmount vs what calculate in the comment?

2021-09-07 13:55 UTC, blackalpacaa commented on test/Mdex_Restricted_StrategyAddBaseTokenOnly.test.ts
> +        // actualLpAmount = 0.015419263215025115
totalSupply in the comment use wrong formula.

2021-09-08 05:02 UTC, spicysquid168 approved these changes

2021-09-08 05:33 UTC, spicysquid168 requested changes

2021-09-08 05:33 UTC, spicysquid168 commented on contracts/6/protocol/strategies/mdex/MdexRestrictedStrategyAddBaseTokenOnly.sol
> +import "../../apis/mdex/SwapMining.sol";
Grouping import
```
import "@openzeppelin/contracts-ethereum-package/contracts/utils/ReentrancyGuard.sol";
import "@openzeppelin/contracts-ethereum-package/contracts/Initializable.sol";
import "@openzeppelin/contracts-ethereum-package/contracts/access/Ownable.sol";

import "../../apis/mdex/IMdexRouter.sol";
import "../../apis/mdex/IMdexFactory.sol";
import "../../apis/mdex/SwapMining.sol";
import "@pancakeswap-libs/pancake-swap-core/contracts/interfaces/IPancakePair.sol";

import "../../interfaces/IStrategy.sol";
import "../../interfaces/IWorker.sol";

import "../../../utils/SafeToken.sol";
import "../../../utils/AlpacaMath.sol";
```

2021-09-08 05:33 UTC, spicysquid168 commented on contracts/6/protocol/strategies/mdex/MdexRestrictedStrategyAddBaseTokenOnly.sol
> +  /// @dev Get all trading rewards.
`/// @dev Get trading rewards by pIds`

2021-09-08 05:33 UTC, spicysquid168 commented on contracts/6/protocol/strategies/mdex/MdexRestrictedStrategyAddBaseTokenOnly.sol
> +  /// @dev Formular for calculating optimal swap come from UniSwapV2
`///dev Formula for calculating one-sided optimal swap. Return the amount that needs to be swapped`

2021-09-08 05:33 UTC, spicysquid168 commented on contracts/6/protocol/strategies/mdex/MdexRestrictedStrategyAddBaseTokenOnly.sol
> +  /// @param fee trading fee of pair.
`/// @param fee trading fee of the pair.`

2021-09-08 05:33 UTC, spicysquid168 commented on contracts/6/protocol/strategies/mdex/MdexRestrictedStrategyAddBaseTokenOnly.sol
> +  /// @param rIn reserve of baseToken in pair.
`/// @param rIn reserve of baseToken in the pair.`

2021-09-08 05:33 UTC, spicysquid168 commented on contracts/6/protocol/strategies/mdex/MdexRestrictedStrategyAddBaseTokenOnly.sol
> +  /// @param balance balance of baseToken in worker.
`/// @param balance balance of baseToken from worker`

2021-09-08 12:02 UTC, spicysquid168 requested changes

2021-09-08 12:02 UTC, spicysquid168 commented on contracts/6/protocol/strategies/mdex/MdexRestrictedStrategyAddBaseTokenOnly.sol
> +import "../../interfaces/ISwapMining.sol";
move it to `Mdex` group below `IPancakePair`

2021-09-09 04:33 UTC, spicysquid168 approved these changes

2021-09-09 06:21 UTC, merged