[WIP][feat/mdex-integration][feat] mdex worker
alpaca-finance/bsc-alpaca-contract pull request #122
Opened 2021-08-31 05:00 UTC by sora-alpaca

## Description

## Why?

## ChangeLogs:

### Link to story (if available)

2021-09-06 05:07 UTC, spicysquid168 commented on contracts/6/protocol/workers/mdex/MdexWorker.sol
> +    uint256 fee = feeDenom - factory.getPairFees(address(lpToken));
Use SafeMath to prevent subtraction overflow
`feeDenom.sub(factory.getPairFees(address(lpToken));`

2021-09-06 05:07 UTC, spicysquid168 commented on contracts/6/protocol/workers/mdex/MdexWorker.sol
> +    // 4. Convert all FarmingToken to BaseToken and return total BaseToken.
Adjust comment

2021-09-06 05:07 UTC, spicysquid168 commented on contracts/6/protocol/workers/mdex/MdexWorker.sol
> +    router.swapExactTokensForTokens(reward.sub(bounty), 0, getReinvestPath(), address(this), now);
We have swap here too. Hence, better have `withdrawSwapMining` function and `getSwapMiningReward` in this worker too

2021-09-06 05:07 UTC, spicysquid168 commented on contracts/6/protocol/workers/mdex/MdexWorker.sol
> +    if (treasuryAccount != address(0) && treasuryBountyBps != 0)
This line when we were migrate from the older version to the new one. Please remove it as `treasuryAccount` and `treasuryBountyBps` won't be default values as it is assigned when initialized

2021-09-06 05:07 UTC, spicysquid168 commented on test/Vault_MdexWorker.test.ts
> +        });
Should add the case where Mdex change fee during worker is live

2021-09-06 05:07 UTC, spicysquid168 commented on test/Vault_MdexWorker.test.ts
> +        });
assert health to see if it is reflected the change on Mdex or not

2021-09-06 13:08 UTC, jr-alpaca commented on contracts/6/protocol/workers/mdex/MdexWorker02.sol
> +  function getMiningRewards() public view returns (uint256) {
receive pIds as param

2021-09-07 06:23 UTC, jr-alpaca commented on contracts/6/protocol/workers/mdex/MdexWorker02.sol
> +    require(
address(lpToken).safeTransfer(...)

2021-09-07 06:24 UTC, jr-alpaca commented on contracts/6/protocol/workers/mdex/MdexWorker02.sol
> +    lpToken.transfer(address(liqStrat), lpToken.balanceOf(address(this)));
address(lpToken).safeTransfer(...)

2021-09-08 05:07 UTC, spicysquid168 requested changes

2021-09-08 05:07 UTC, spicysquid168 commented on contracts/6/protocol/workers/mdex/MdexWorker02.sol
> +import "../../apis/mdex/BSCPool.sol";
Create `IBSCPool.sol` and import interface only

2021-09-08 05:07 UTC, spicysquid168 commented on contracts/6/protocol/workers/mdex/MdexWorker02.sol
> +import "../../apis/mdex/SwapMining.sol";
Create `ISwapMining.sol` and import interface only

2021-09-08 12:04 UTC, spicysquid168 requested changes

2021-09-08 12:04 UTC, spicysquid168 commented on contracts/6/protocol/workers/mdex/MdexWorker02.sol
> +import "../../interfaces/ISwapMining.sol";
move it to Mdex related group

2021-09-08 12:04 UTC, spicysquid168 commented on contracts/6/protocol/workers/mdex/MdexWorker02.sol
> +import "../../interfaces/IBSCPool.sol";
move it to Mdex related group under IPancakePair

2021-09-09 04:41 UTC, spicysquid168 requested changes

2021-09-09 04:41 UTC, spicysquid168 commented on contracts/6/protocol/workers/mdex/MdexWorker02.sol
> +      "MdexWorker02::setRewardPath:: rewardPath must start with CAKE and end with beneficialVault token"
rewardPath must start with MDX

2021-09-09 04:41 UTC, spicysquid168 commented on contracts/6/protocol/workers/mdex/MdexWorker02.sol
> +  /// @param _reinvestThreshold - The threshold to be reinvested if pendingCake pass over.
The threshold to be revinested if reward pass over

2021-09-09 04:41 UTC, spicysquid168 commented on contracts/6/protocol/workers/mdex/MdexWorker02.sol
> +  /// @dev Return maximum output given the input amount and the status of Uniswap reserves.
and the status of MDEX reserves

2021-09-09 05:37 UTC, spicysquid168 approved these changes

2021-09-09 05:39 UTC, spicysquid168 approved these changes

2021-09-09 06:22 UTC, merged