[WIP][mdex-integration][feat] add mdex twosidesoptimal strategy
alpaca-finance/bsc-alpaca-contract pull request #123
Opened 2021-08-31 05:19 UTC by jr-alpaca

## Description

- add MdexRestrictedStrategyAddTwosidesOptimal Strategy
## Why?

## ChangeLogs:

### Link to story (if available)

2021-08-31 09:33 UTC, sora-alpaca requested changes

2021-08-31 09:33 UTC, sora-alpaca commented on contracts/6/protocol/strategies/mdex-restricted/MdexRestrictedStrategyAddTwosidesOptimal.sol
> +contract MdexRestrictedStrategyAddTwosidesOptimal is OwnableUpgradeSafe, ReentrancyGuardUpgradeSafe, IStrategy {
```suggestion
contract MdexRestrictedStrategyAddTwoSidesOptimal is OwnableUpgradeSafe, ReentrancyGuardUpgradeSafe, IStrategy {
```

2021-08-31 09:34 UTC, sora-alpaca commented
is file name correct?

MdexRestrictedStrategyAddTwo`sides`Optimal => MdexRestrictedStrategyAddTwo`Sides`Optimal

2021-09-06 05:23 UTC, spicysquid168 requested changes

2021-09-06 05:23 UTC, spicysquid168 commented on contracts/6/protocol/strategies/mdex-restricted/MdexRestrictedStrategyAddTwosidesOptimal.sol
> +    uint256 fee = factory.getPairFees(address(lpToken));
move getPairFees to right before optimalDeposit

2021-09-06 05:23 UTC, spicysquid168 commented on contracts/6/protocol/strategies/mdex-restricted/MdexRestrictedStrategyAddTwosidesOptimal.sol
> +      lpToken.transfer(msg.sender, lpToken.balanceOf(address(this))),
`address(lpToken).safeTransfer()`

2021-09-06 10:17 UTC, spicysquid168 commented on contracts/6/protocol/strategies/mdex-restricted/MdexRestrictedStrategyAddTwosidesOptimal.sol
> +  address public mdx;
`mdx` after router

2021-09-06 10:17 UTC, spicysquid168 commented on contracts/6/protocol/strategies/mdex-restricted/MdexRestrictedStrategyAddTwosidesOptimal.sol
> +  function getMiningRewards() public view returns (uint256) {
received pIds from caller to avoid uncontrollable pool.length that may cause out of gas

2021-09-06 10:17 UTC, spicysquid168 commented on contracts/6/protocol/strategies/mdex-restricted/MdexRestrictedStrategyAddTwosidesOptimal.sol
> +    for (uint256 pid = 0; pid < poolLength; ++pid) {
pid++

2021-09-08 05:10 UTC, spicysquid168 requested changes

2021-09-08 05:10 UTC, spicysquid168 commented on contracts/6/protocol/strategies/mdex-restricted/MdexRestrictedStrategyAddTwosidesOptimal.sol
> +import "../../apis/mdex/SwapMining.sol";
Create `ISwapMining.sol` and import it instead

2021-09-08 05:10 UTC, spicysquid168 commented on contracts/6/protocol/strategies/mdex-restricted/MdexRestrictedStrategyAddTwosidesOptimal.sol
> +  /// @dev Get all trading rewards.
`/// @dev Get trading rewards by pIds`

2021-09-08 05:22 UTC, spicysquid168 requested changes

2021-09-08 05:22 UTC, spicysquid168 commented on contracts/6/protocol/strategies/mdex-restricted/MdexRestrictedStrategyAddTwosidesOptimal.sol
> +import "@pancakeswap-libs/pancake-swap-core/contracts/interfaces/IPancakePair.sol";
Grouping import order
```
import "@openzeppelin/contracts-ethereum-package/contracts/utils/ReentrancyGuard.sol";
import "@openzeppelin/contracts-ethereum-package/contracts/Initializable.sol";
import "@openzeppelin/contracts-ethereum-package/contracts/access/Ownable.sol";

import "../../apis/mdex/IMdexFactory.sol";
import "../../apis/mdex/IMdexRouter.sol";
import "@pancakeswap-libs/pancake-swap-core/contracts/interfaces/IPancakePair.sol";
import "../../apis/mdex/SwapMining.sol";

import "../../interfaces/IStrategy.sol";
import "../../interfaces/IVault.sol";
import "../../interfaces/IWorker.sol";

import "../../../utils/SafeToken.sol";
import "../../../utils/AlpacaMath.sol";
```

2021-09-09 04:42 UTC, spicysquid168 approved these changes

2021-09-09 04:44 UTC, spicysquid168 commented
There is 1 pending comment from @sora-alpaca please check. If ok then please change to approve.

2021-09-09 06:31 UTC, merged