[mdex-integration][feat] : liquidate strategy
alpaca-finance/bsc-alpaca-contract pull request #126
Opened 2021-08-31 06:47 UTC by abc-alpaca

## Description

## Why?

## ChangeLogs:

### Link to story (if available)

2021-09-03 11:41 UTC, jr-alpaca commented on contracts/6/protocol/strategies/mdex-restricted/MdexRestrictedStrategyLiquidate.sol
> +  address public mdx;
declare mdx after router in line 35

2021-09-03 11:43 UTC, jr-alpaca commented on contracts/6/protocol/strategies/mdex-restricted/MdexRestrictedStrategyLiquidate.sol
> +  function initialize(IMdexRouter _router, address _mdx) external initializer {
please add comment for _mdx initialize agrument

2021-09-03 11:47 UTC, jr-alpaca commented on test/Mdex_Restricted_StrategyLiquidate.test.ts
> +// FIXME do declare variable
remove this comment

2021-09-06 09:02 UTC, jr-alpaca commented on contracts/6/protocol/strategies/mdex-restricted/MdexRestrictedStrategyLiquidate.sol
> +  }
add getMiningRewards()

2021-09-06 09:05 UTC, jr-alpaca commented on test/Mdex_Restricted_StrategyLiquidate.test.ts
> +      expect(mdexTokenAfter.sub(mdexTokenBefore)).to.be.bignumber.eq("877200000000000000000");
assert mdx amount change with getMiningRewards()

2021-09-06 13:45 UTC, jr-alpaca commented on contracts/6/protocol/strategies/mdex-restricted/MdexRestrictedStrategyLiquidate.sol
> +  /// @param pids pool IDs of all to be get rewards,
/// @param pids pool IDs of all to be get rewards.
small typo

2021-09-08 05:15 UTC, spicysquid168 requested changes

2021-09-08 05:15 UTC, spicysquid168 commented on contracts/6/protocol/strategies/mdex-restricted/MdexRestrictedStrategyLiquidate.sol
> +import "../../apis/mdex/SwapMining.sol";
Create `ISwapMining.sol` and import it instead

2021-09-08 05:15 UTC, spicysquid168 commented on contracts/6/protocol/strategies/mdex-restricted/MdexRestrictedStrategyLiquidate.sol
> +  /// @notice get Mining reward
`/// @dev Get mining rewards by pIds`

2021-09-08 05:15 UTC, spicysquid168 commented on contracts/6/protocol/strategies/mdex-restricted/MdexRestrictedStrategyLiquidate.sol
> +  /// @param pids pool IDs of all to be get rewards.
`/// @param pool ids to retrieve reward amount.`

2021-09-09 04:46 UTC, spicysquid168 approved these changes

2021-09-09 06:35 UTC, merged