[main][test] add example when calling work as whitelisted contract
alpaca-finance/bsc-alpaca-contract pull request #174
Opened 2021-12-20 09:38 UTC by ricardo-alpaca

## Description
Add an example on how to call `Vault.work()` from a whitelisted contract to open a position.

## Why?
Because current test has not cover this scenario and this would be a starting example for any protocol that wish to integrate with Alpaca's LYF product.

## ChangeLogs:

### Link to story (if available)

2021-12-29 10:57 UTC, spicysquid168 requested changes

2021-12-29 10:57 UTC, spicysquid168 commented on contracts/6/protocol/mock/MockWorkCaller.sol
> +import "../Vault.sol";
Use `IVault` instead

2021-12-29 10:57 UTC, spicysquid168 commented on contracts/6/protocol/mock/MockWorkCaller.sol
> +    vault.token().safeApprove(address(vault), uint256(-1));
move this to constructor

2022-01-25 08:18 UTC, ricardo-alpaca commented on contracts/6/protocol/mock/MockWorkCaller.sol
> +import "../Vault.sol";
Well, `IVault` does not have `nextPositionID()`. So, I used `Vault` instead.

2022-01-25 08:33 UTC, alpanaca submitted a review, later dismissed

2022-01-25 08:51 UTC, ricardo-alpaca commented on contracts/6/protocol/mock/MockWorkCaller.sol
> +import "../Vault.sol";
chane to IVault02

2022-01-26 05:38 UTC, alpanaca approved these changes

2022-08-02 04:41 UTC, closed without merging