[feat] delta nuetral worker
alpaca-finance/bsc-alpaca-contract pull request #184
Opened 2022-01-19 08:02 UTC by sora-alpaca

## Description

## Why?

## ChangeLogs:

### Link to story (if available)

2022-01-19 13:39 UTC, alpanaca commented on contracts/8.10/protocol/workers/delta-neutral/DeltaNeutralWorker02.sol
> +  function getMktSellAmount(
Remove this.

2022-01-20 04:39 UTC, sora-alpaca commented on contracts/8.10/protocol/workers/delta-neutral/DeltaNeutralWorker02.sol
> +    masterChef.withdraw(pid, 0);
_masterChefWithdraw

2022-01-20 04:39 UTC, sora-alpaca commented on contracts/8.10/protocol/workers/delta-neutral/DeltaNeutralWorker02.sol
> +    masterChef.deposit(pid, lpToken.balanceOf(address(this)));
_masterChefDeposit

2022-01-20 04:39 UTC, sora-alpaca commented on contracts/8.10/protocol/workers/delta-neutral/DeltaNeutralWorker02.sol
> +    // 2. Convert this position back to LP tokens.
fix comment

2022-01-26 09:05 UTC, alpanaca requested changes

2022-01-26 09:51 UTC, jr-alpaca commented on contracts/8.10/protocol/interfaces/IERC20.sol
> +pragma solidity 0.8.10;
license

2022-01-26 09:52 UTC, jr-alpaca commented on contracts/8.10/protocol/workers/DeltaNeutralMdexWorker02.sol
> +// SPDX-License-Identifier: MIT
// SPDX-License-Identifier: BUSL

2022-01-26 09:53 UTC, jr-alpaca commented on contracts/8.10/protocol/workers/DeltaNeutralPancakeWorker02.sol
> +// SPDX-License-Identifier: MIT
// SPDX-License-Identifier: BUSL

2022-01-26 11:38 UTC, abc-alpaca commented on contracts/8.10/protocol/interfaces/IBSCPool.sol
> +// SPDX-License-Identifier: MIT
```suggestion
// SPDX-License-Identifier: BUSL
```

2022-01-26 11:39 UTC, abc-alpaca commented on contracts/8.10/protocol/interfaces/IMdexSwapMining.sol
> +// SPDX-License-Identifier: MIT
```suggestion
// SPDX-License-Identifier: BUSL```

2022-01-26 11:40 UTC, abc-alpaca commented on contracts/8.10/protocol/interfaces/IPancakeMasterChef.sol
> +// SPDX-License-Identifier: MIT
```suggestion
// SPDX-License-Identifier: BUSL
```

2022-01-26 11:41 UTC, abc-alpaca commented on contracts/8.10/protocol/interfaces/IPancakeRouter02.sol
> +pragma solidity 0.8.10;
// SPDX-License-Identifier: BUSL
/**
  ∩~~~~∩ 
  ξ ･×･ ξ 
  ξ　~　ξ 
  ξ　　 ξ 
  ξ　　 “~～~～〇 
  ξ　　　　　　 ξ 
  ξ ξ ξ~～~ξ ξ ξ 
　 ξ_ξξ_ξ　ξ_ξξ_ξ
Alpaca Fin Corporation
*/

2022-01-26 11:41 UTC, abc-alpaca commented on contracts/8.10/protocol/interfaces/IStrategy.sol
> +// SPDX-License-Identifier: MIT
license

2022-01-26 11:42 UTC, abc-alpaca commented on contracts/8.10/protocol/interfaces/IWorker.sol
> +// SPDX-License-Identifier: MIT
```suggestion
// SPDX-License-Identifier: BUSL
```

2022-01-26 11:42 UTC, abc-alpaca commented on contracts/8.10/protocol/interfaces/IWorker02.sol
> +// SPDX-License-Identifier: MIT
```suggestion
// SPDX-License-Identifier: BUSL
```

2022-01-26 11:45 UTC, abc-alpaca commented on contracts/8.10/protocol/workers/DeltaNeutralMdexWorker02.sol
> +    IPriceHelper _lpCalculator
```suggestion
    IPriceHelper _priceHelper
```

2022-01-26 11:56 UTC, abc-alpaca commented on test/integrations/protocol/workers/delta-neutral/Vault_DeltaNeutralMdexWorker02.test.ts
> +    // TODO: should we remove this?
```suggestion
    remove comment 
```

2022-01-26 12:06 UTC, abc-alpaca commented on contracts/8.10/protocol/workers/DeltaNeutralPancakeWorker02.sol
> +    IPriceHelper _lpCalculator
```suggestion
    IPriceHelper _priceHelper
```

2022-01-27 04:31 UTC, alpanaca requested changes

2022-01-27 04:31 UTC, alpanaca commented on test/integrations/protocol/workers/delta-neutral/Vault_DeltaNeutralPancakeWorker02.test.ts
> +    // TOFIXTEST: should we remove this?
We shouldn't remove this. This is the sanity check before more complex test

2022-01-27 04:31 UTC, alpanaca commented on test/integrations/protocol/workers/delta-neutral/Vault_DeltaNeutralPancakeWorker02.test.ts
> +  context("when user uses LYF", async () => {
```suggestion
  context("when user DeltaNet use LYF", async () => {
```

2022-01-27 04:31 UTC, alpanaca commented on test/integrations/protocol/workers/delta-neutral/Vault_DeltaNeutralPancakeWorker02.test.ts
> +    context("when user is EOA", async () => {
We might want to keep this "scenario"

When user is EOA, they can't interact with this worker since we only allow for delta net vault.

2022-01-27 04:31 UTC, alpanaca commented on test/integrations/protocol/workers/delta-neutral/Vault_DeltaNeutralPancakeWorker02.test.ts
> +        // TODO: remove because this test case test about work factor
I think we should keep this. Work factor functionality should be there but we just change the param to allow higher work factor than normal.

2022-01-27 04:31 UTC, alpanaca commented on test/integrations/protocol/workers/delta-neutral/Vault_DeltaNeutralPancakeWorker02.test.ts
> +        // TODO: remove because this test case test about work factor
However, be careful with permission since we only certain address to work on this worker. Alice/Bob shouldn't be able to work on this.

2022-01-27 04:31 UTC, alpanaca commented on test/integrations/protocol/workers/delta-neutral/Vault_DeltaNeutralPancakeWorker02.test.ts
> +        // TODO: remove this because this one check how user manage position
Can remove this. However, should have test cases to cover how partial close behave.

2022-01-27 04:31 UTC, alpanaca commented on test/integrations/protocol/workers/delta-neutral/Vault_DeltaNeutralPancakeWorker02.test.ts
> +        // TODO: remove this because this one check how user manage position
Can be removed.

2022-01-27 04:31 UTC, alpanaca commented on test/integrations/protocol/workers/delta-neutral/Vault_DeltaNeutralPancakeWorker02.test.ts
> +        it("should be able to liquidate bad position", async () => {
Fix the name to reflect how test was asserted

2022-01-27 04:31 UTC, alpanaca commented on test/integrations/protocol/workers/delta-neutral/Vault_DeltaNeutralPancakeWorker02.test.ts
> +        it("should liquidate user position correctly", async () => {
Fix the name to reflect how test was asserted

2022-01-27 04:31 UTC, alpanaca commented on test/integrations/protocol/workers/delta-neutral/Vault_DeltaNeutralPancakeWorker02.test.ts
> +          // QUESTION: do we need this test?
Yes. As mentioned earlier, the work factor functionality suppose to be functioning.

2022-01-27 04:31 UTC, alpanaca commented on test/integrations/protocol/workers/delta-neutral/Vault_DeltaNeutralPancakeWorker02.test.ts
> +        // QUESTION: Do we need this test?
Adding collateral is one of the essential part in delta net. Need to cover this.

2022-01-27 11:13 UTC, jr-alpaca commented on contracts/8.10/protocol/workers/DeltaNeutralPancakeWorker02.sol
> +/// @title DeltaNeutralPancakeWorker02 is a PancakeswapV2Worker with with reinvest-optimized and beneficial vault buyback functionalities
typo: is a PancakeswapV2Worker with reinvest

2022-01-27 11:22 UTC, jr-alpaca approved these changes

2022-01-27 11:24 UTC, merged