[main][feat]: claim at mini fairlaunch
alpaca-finance/bsc-alpaca-contract pull request #253
Opened 2022-03-24 06:00 UTC by abc-alpaca

## Description
- [env] update env.example 
- [contract] add interface of miniFL in 8.10 
- [contract for test] add mock MiniFL in contract for test 
- [contract] change claim when reinvest from fairlaunch to miniFL (contract)
- [test] remove calculation part alpaca reward part (using mockMiniFL)

## Why?

## ChangeLogs:

### Link to story (if available)

2022-03-24 09:43 UTC, jr-alpaca commented on contracts/8.10/protocol/DeltaNeutralVault02.sol
> +import "hardhat/console.sol";
please remove import console.sol

2022-03-24 09:47 UTC, jr-alpaca commented on contracts/8.10/protocol/interfaces/IMiniFL.sol
> +// SPDX-License-Identifier: MIT
```suggestion
// SPDX-License-Identifier: BUSL
```

2022-03-24 09:48 UTC, jr-alpaca commented on contracts/8.10/token/interfaces/IRewarder.sol
> +// SPDX-License-Identifier: MIT
```suggestion
// SPDX-License-Identifier: BUSL
```

2022-03-24 09:48 UTC, jr-alpaca commented on contracts/8.10/token/interfaces/IMiniFL.sol
> +// SPDX-License-Identifier: MIT
```suggestion
// SPDX-License-Identifier: BUSL
```

2022-03-24 12:30 UTC, alpanaca requested changes

2022-03-24 12:30 UTC, alpanaca commented on contracts/8.10/protocol/DeltaNeutralVault02.sol
> +    address _fairLaunchAddress = config.fairLaunchAddr();
```suggestion
    address _miniFLAddress= config.fairLaunchAddr();
```

2022-03-24 12:30 UTC, alpanaca commented on contracts/8.10/protocol/DeltaNeutralVault02.sol
> +    IMiniFL(_fairLaunchAddress).harvest(IVault(stableVault).fairLaunchPoolId());
```suggestion
    IMiniFL(_miniFLAddress).harvest(IVault(stableVault).fairLaunchPoolId());
```

2022-03-24 12:30 UTC, alpanaca commented on contracts/8.10/protocol/DeltaNeutralVault02.sol
> +    IMiniFL(_fairLaunchAddress).harvest(IVault(assetVault).fairLaunchPoolId());
```suggestion
    IMiniFL(_miniFLAddress).harvest(IVault(assetVault).fairLaunchPoolId());
```

2022-03-24 12:32 UTC, sora-alpaca commented on .env.example
> +FANTOM_TESTNET_PRIVATE_KEY="xxx"
should it be FANTOM or FTM

2022-03-24 12:34 UTC, alpanaca commented on .env.example
> +FANTOM_TESTNET_PRIVATE_KEY="xxx"
Should be any but keep it consistent.

2022-03-24 12:34 UTC, abc-alpaca commented on .env.example
> +FANTOM_TESTNET_PRIVATE_KEY="xxx"
FANTOM is correct

2022-03-24 12:40 UTC, alpanaca submitted a review, later dismissed

2022-03-24 13:13 UTC, spicysquid168 commented
I think the only that need to be done in this PR is to write a test on `DeltaNeutralVault` + `MiniFL`. Other parts can be left out.

2022-03-24 13:13 UTC, spicysquid168 requested changes

2022-03-24 13:13 UTC, spicysquid168 commented on contracts/8.10/protocol/DeltaNeutralVault02.sol
> +contract DeltaNeutralVault02 is ERC20Upgradeable, ReentrancyGuardUpgradeable, OwnableUpgradeable {
I don't think we need to add `DeltaNeutralVault02` at all. The only diff is just importing the interface of liquidity mining contract which in fact no need to be changed as the function that need to make a call to liquidity mining is fully compatible in `DeltaNeutralVault` as well

2022-03-24 13:13 UTC, spicysquid168 commented on contracts/8.10/protocol/interfaces/IMiniFL.sol
> +pragma solidity 0.8.10;
This also no need

2022-03-25 05:35 UTC, spicysquid168 approved these changes

2022-03-25 06:19 UTC, jr-alpaca approved these changes

2022-03-25 07:27 UTC, merged