Feat/nft staking
alpaca-finance/bsc-alpaca-contract pull request #269
Opened 2022-04-07 06:36 UTC by blueAnAlpaca

## Description?
- Change NFTStaking solidity version from 0.6.6 to 0.8.13 and make sure it is compilable. 
- Add more test case and test whether it passes the test or not

## ChangeLogs:
- Upgrading some dependencies are required in order to make the 0.8.13 test runnable (waffle, chai, hardhat-ethers, ethers)
- There is a missing key in env.example: `QA_PRIVATE_KEY`

2022-04-07 07:30 UTC, alpanaca commented on contracts/8.13/nft-staking/NFTStaking.sol
> +    require(msg.sender == tx.origin, "NFTStaking::onlyEOA::not eoa");
Please use custom error.

 https://blog.soliditylang.org/2021/04/21/custom-errors/

2022-04-07 07:33 UTC, alpanaca commented on contracts/6/protocol/workers/SingleAssetWorkerConfig.sol
> +    } else {
"else here is unnecessary

2022-04-07 07:34 UTC, alpanaca commented on contracts/6/protocol/workers/SingleAssetWorkerConfig.sol
> +    } else {
"else" here is unnecessary

2022-04-07 07:55 UTC, alpanaca submitted a review, later dismissed

2022-04-07 07:55 UTC, alpanaca commented on contracts/6/protocol/workers/WorkerConfig.sol
> +  function setBoostedLeverage(address[] calldata addrs, BoostedLeverage[] calldata configs) external onlyOwner {
What is this "addrs" for? worker address? If yes, would be easier to read if we call it workerAddrs?

2022-04-07 07:55 UTC, alpanaca commented on contracts/6/protocol/workers/WorkerConfig.sol
> +    } else {
Else is unnecessary

2022-04-07 07:55 UTC, alpanaca commented on contracts/8.13/nft-staking/NFTStaking.sol
> +import "./interfaces/INFTStaking.sol";
```suggestion

import "./interfaces/INFTStaking.sol";
```

2022-04-07 07:55 UTC, alpanaca commented on contracts/8.13/nft-staking/NFTStaking.sol
> +  event LogStakeNFT(address indexed staker, bytes32 indexed poolId, address nftAddress, uint256 nftTokenId);
Follow the ordering convention.

/// @notice Libraries

/// @notice Errors

/// @notice States

/// @notice Events

2022-04-07 07:55 UTC, alpanaca commented on contracts/8.13/nft-staking/NFTStaking.sol
> +  event LogUnstakeNFT(address indexed staker, bytes32 indexed poolId, address nftAddress, uint256 nftTokenId);
```suggestion
  event LogUnstakeNFT(address indexed _staker, bytes32 indexed _poolId, address _nftAddress, uint256 _nftTokenId);
```

2022-04-07 07:55 UTC, alpanaca commented on contracts/8.13/nft-staking/NFTStaking.sol
> +    mapping(address => uint256) stakeNFTToken; // Mapping of NFT token addresses that are allowed to stake in this pool
```suggestion
    // Mapping of NFT token addresses that are allowed to stake in this pool
    mapping(address => uint256) eligibleToken; 
```

2022-04-07 07:55 UTC, alpanaca commented on contracts/8.13/nft-staking/NFTStaking.sol
> +      poolInfo[_poolId].stakeNFTToken[_stakeNFTToken[_i]] = _allowance[_i];
Since you treat this _allowance as a 0 or 1. It's good to check that first.

2022-04-07 07:55 UTC, alpanaca commented on contracts/8.13/nft-staking/NFTStaking.sol
> +    emit LogAddPool(_msgSender(), _poolId, _stakeNFTToken);
I'd rather emit log inside the loop.

2022-04-07 07:55 UTC, alpanaca commented on contracts/8.13/nft-staking/NFTStaking.sol
> +    require(msg.sender == tx.origin, "NFTStaking::onlyEOA::not eoa");
inconsistent between msg.sender and _msgSender(); Please use only one.

2022-04-07 07:55 UTC, alpanaca commented on contracts/8.13/nft-staking/NFTStaking.sol
> +    NFTStakingInfo memory toBeSentBackNft = userStakingNFT[_poolId][_msgSender()];
```suggestion
    NFTStakingInfo memory _toBeSentBackNft = userStakingNFT[_poolId][_msgSender()];
```

2022-04-07 13:30 UTC, blueAnAlpaca commented on contracts/8.13/nft-staking/NFTStaking.sol
> +    emit LogAddPool(_msgSender(), _poolId, _stakeNFTToken);
Isn't that too redundant?

2022-04-07 13:32 UTC, blueAnAlpaca commented on contracts/8.13/nft-staking/NFTStaking.sol
> +    require(msg.sender == tx.origin, "NFTStaking::onlyEOA::not eoa");
Is there any rules for using the `msg.sender`? Seem like both of them are use all over the place.

2022-04-07 13:44 UTC, alpanaca commented on contracts/8.13/nft-staking/NFTStaking.sol
> +    require(msg.sender == tx.origin, "NFTStaking::onlyEOA::not eoa");
https://forum.openzeppelin.com/t/why-use-msgsender-rather-than-msg-sender/4370

Well, it depends on the context. Let's say if we're to send some kind of token back to transaction initiator rather than the gas payer. We want to use msg.sender.

2022-04-07 13:45 UTC, alpanaca commented on contracts/8.13/nft-staking/NFTStaking.sol
> +    require(msg.sender == tx.origin, "NFTStaking::onlyEOA::not eoa");
Not a hard requirement to change tho. I'll let other comment.

2022-04-08 03:09 UTC, ricardo-alpaca commented on contracts/6/protocol/workers/WorkerConfig.sol
> +  function setBoostedLeverage(address[] calldata addrs, BoostedLeverage[] calldata configs) external onlyOwner {
They are worker addresses. It would be better to give it a better name.

2022-04-08 06:41 UTC, ricardo-alpaca commented on contracts/8.13/nft-staking/NFTStaking.sol
> +    emit LogAddPool(_msgSender(), _poolId, _stakeNFTToken);
One event emission should be enough here.

2022-04-18 07:56 UTC, ricardo-alpaca commented on contracts/6/protocol/workers/WorkerConfig.sol
> +  INFTBoostedLeverageController nftBoostedLeverageController;
```suggestion
  INFTBoostedLeverageController public nftBoostedLeverageController;
```

2022-04-18 07:57 UTC, ricardo-alpaca commented on contracts/6/protocol/workers/SingleAssetWorkerConfig.sol
> +  INFTBoostedLeverageController nftBoostedLeverageController;
```suggestion
  INFTBoostedLeverageController public nftBoostedLeverageController;
```

2022-04-18 07:58 UTC, ricardo-alpaca commented on contracts/8.13/nft-staking/NFTBoostedLeverageController.sol
> +  INFTStaking nftStaking;
```suggestion
  INFTStaking public nftStaking;
```

2022-04-18 07:59 UTC, ricardo-alpaca commented on contracts/8.13/nft-staking/NFTBoostedLeverageController.sol
> +    nftStakingContractAddress = _nftStakingContractAddress;
The initializer should just accept `INFTStaking _nftStaking` and assign to `nftStaking`. There is no need for `nftStakingContractAddress`.

2022-04-18 08:05 UTC, ricardo-alpaca commented on contracts/8.13/nft-staking/NFTBoostedLeverageController.sol
> +      if (uniquePoolIds[_poolIds[_i]] != 0) revert NFTBoostedLeverageController_PoolAlreadyListed();
Using EnumerableSet could make this easier https://docs.openzeppelin.com/contracts/4.x/api/utils#EnumerableSet
You could also remove `poolId` too.

2022-04-18 08:07 UTC, ricardo-alpaca commented on contracts/8.13/nft-staking/NFTBoostedLeverageController.sol
> +    for (uint256 _i; _i < poolIds.length; _i++) {
This would set a particular worker of every poolId to the same `boostedWorkFactor` and same `boostedKillFactor`. We would want to be more flexible than this.

2022-04-18 08:08 UTC, ricardo-alpaca commented on contracts/8.13/nft-staking/NFTBoostedLeverageController.sol
> +        if (boostedWorkFactors[poolIds[_i]][_worker] != 0) {
This is check is not needed if this function is going to return zero anyways.

2022-04-18 16:27 UTC, blueAnAlpaca commented on contracts/8.13/nft-staking/NFTBoostedLeverageController.sol
> +    for (uint256 _i; _i < poolIds.length; _i++) {
If `worker` can have different `boostNumber` that depend to the pool. This will cause conflict when `getBoostedFactor` is called since `workerConfig` only knows the owner and worker (sorry if this sound confusing 😅)

2022-04-20 09:59 UTC, Alpaca-Cappuccino commented on contracts/6/protocol/workers/WorkerConfig.sol
> +    }
if (_boostedKillFactor > 0)  return _boostedKillFactor;
return uint256(workers[worker].killFactor);

2022-04-20 10:01 UTC, Alpaca-Cappuccino commented on contracts/6/protocol/workers/WorkerConfig.sol
> +  }
if (_boostedWorkFactor > 0) return _boostedWorkFactor;
return uint256(workers[worker].workFactor);

2022-05-15 08:51 UTC, ricardo-alpaca commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +    IERC721Upgradeable(_poolId).safeTransferFrom(address(this), msg.sender, _nftTokenId);
Add check if the withdrawing NFT has passed the locked period.

2022-05-15 08:51 UTC, ricardo-alpaca commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +  function stakeNFT(
We will need another function to extend the lock period of the staked NFT.

2022-05-15 08:54 UTC, ricardo-alpaca commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +    }
Remove these as it would not passed the check of `if (!poolInfo[_poolId].isInit) revert NFTStaking_PoolNotExist();`
[NFTStaking Issue 2]

2022-05-15 08:55 UTC, ricardo-alpaca commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +    if (poolInfo[_poolId].isInit) revert NFTStaking_PoolAlreadyExist();
addPool should check that poolId is non-zero. [NFTStaking Issue 3]

2022-05-15 08:55 UTC, ricardo-alpaca commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +    IERC721Upgradeable(_poolId).safeTransferFrom(msg.sender, address(this), _nftTokenId);
safeTransferFrom should be done after all the state changes. [NFTStaking Issue 4]

2022-05-15 08:56 UTC, ricardo-alpaca commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +    IERC721Upgradeable(_poolId).safeTransferFrom(address(this), msg.sender, _nftTokenId);
safeTransferFrom should be done after all the state changes. [NFTStaking Issue 4]
move them to almost the last line before emitting event

2022-05-15 08:57 UTC, ricardo-alpaca commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +    address _poolId,
change all `_poolId` and `poolId` to `nftAddress` to avoid confusion [NFTStaking Issue 5]

2022-05-15 08:58 UTC, ricardo-alpaca commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +    IERC721Upgradeable(_poolId).safeTransferFrom(msg.sender, address(this), _nftTokenId);
Change all `safeTransferFrom` to `transferFrom` to save gas [NFTStaking Issue 6]

2022-05-15 08:59 UTC, ricardo-alpaca commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +    userStakingPool[msg.sender].add(_poolId);
We will need another mapping to keep track of how many NFT staked in each pool for a user [NFTStaking Issue 8]

2022-05-15 09:00 UTC, ricardo-alpaca commented on solidity/contracts/8.13/nft-staking/NFTBoostedLeverageController.sol
> +      boostedWorkFactors[_poolIds[_i]][_workers[_i]] = _workFactors[_i];
Add max cap for workFactor and killFactor to not exceed `10000` [NFTBoostedLeverageController Issue 1]

2022-05-15 09:02 UTC, ricardo-alpaca commented on solidity/contracts/8.13/nft-staking/NFTBoostedLeverageController.sol
> +  function getBoostedWorkFactor(address _owner, address _worker, uint256 _nftTokenId) external view override returns (uint256) {
`_nftTokenId` is not needed here anymore. We will use `userHighestWeightPoolId` to determine which pool to check the staked NFT. [NFTBoostedLeverageController Issue 2]

2022-05-15 09:03 UTC, ricardo-alpaca commented on solidity/contracts/8.13/nft-staking/NFTBoostedLeverageController.sol
> +    if (INFTStaking(nftStaking).isStaked(poolId, _owner, _nftTokenId)) {
We don't have `_nftTokenId` supplied now. So, we could just check if `poolId` is not `address(0)` which we would have to trust `userHighestWeightPoolId()` to return only a valid and staking poolId (nftAddress). [NFTBoostedLeverageController Issue 3]

2022-05-15 09:07 UTC, ricardo-alpaca commented on solidity/contracts/6/protocol/workers/SingleAssetWorkerConfig.sol
> +  );
Unused, remove.

2022-05-15 09:07 UTC, ricardo-alpaca commented on solidity/contracts/6/protocol/workers/SingleAssetWorkerConfig.sol
> +    nftBoostedLeverageController = _newNFTBoostedLeverageController;
emit event here [SingleAssetWorkerConfig Issue 2]

2022-05-15 09:08 UTC, ricardo-alpaca commented on solidity/contracts/6/protocol/workers/SingleAssetWorkerConfig.sol
> +    address nftStaking,
Remove `nftStaking` as we are relying on `nftBoostedLeverageController` to provide the boosted value now. [NFTBoostedLeverageController Issue 3]

2022-05-15 09:09 UTC, ricardo-alpaca commented on solidity/contracts/6/protocol/workers/SingleAssetWorkerConfig.sol
> +    address nftStaking,
Remove `nftStaking` as we are relying on `nftBoostedLeverageController` to provide the boosted value now. [NFTBoostedLeverageController Issue 3]

2022-05-15 09:09 UTC, ricardo-alpaca commented on solidity/contracts/6/protocol/workers/SingleAssetWorkerConfig.sol
> +    address nftStaking,
Remove `nftStaking` as we are relying on `nftBoostedLeverageController` to provide the boosted value now. [NFTBoostedLeverageController Issue 3]

2022-05-17 03:21 UTC, ricardo-alpaca commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +  mapping(address => address) public userHighestWeightnftAddress;
```suggestion
  mapping(address => address) public userHighestWeightNftAddress;
```

camel case

2022-05-17 03:24 UTC, ricardo-alpaca commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +    userStakingNFT[_depositId] = NFTStakingInfo({ isExist: true, lockPeriod: _lockPeriod, lockUntil: _lockUntil });
I think we can remove `lockPeriod`. I don't see if we would need to use this variable. `lockUntil` would just be enough to determine the release date of the NFT.

2022-05-17 05:16 UTC, blueAnAlpaca commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +    userStakingNFT[_depositId] = NFTStakingInfo({ isExist: true, lockPeriod: _lockPeriod, lockUntil: _lockUntil });
It will be used in `extendLockPeriod`  to check whether the new lock time won't exceed the max lock of each pool.

2022-05-19 06:56 UTC, ricardo-alpaca commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +    uint256 _lockPeriod = _newLockUntil - block.timestamp;
should validate that `_newLockUntil` would not be sooner than the old `_lockUntil`.

2022-05-19 08:42 UTC, ricardo-alpaca commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +    userStakingPool[msg.sender].remove(_nftAddress);
We can't just remove immediately. There might be other tokenId in this pool that has not been unstaked.

2022-05-19 08:43 UTC, ricardo-alpaca commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +    bool isExist;
We could remove `isExist` here to save more space and gas. Non-zero `lockUntil` would mean there is still a staked NFT. If the user want to stake without locking, `lockUntil` would be that block timestamp.

2022-05-20 08:53 UTC, blueAnAlpaca commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +    bool isExist;
How about if the user does not define `lockUntil` ?

2022-05-23 03:24 UTC, ricardo-alpaca commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +    bool isExist;
We would put `block.timestamp` as the `lockUntil` instead. Zero `lockUntil` would mean the stake does not exist.

2022-05-30 07:13 UTC, alpanaca requested changes

2022-05-30 07:13 UTC, alpanaca commented on solidity/contracts/8.13/nft-staking/NFTBoostedLeverageController.sol
> +    return 0;
```suggestion
    return nftAddress != address(0) ? boostedWorkFactors[nftAddress][_worker] : 0;
```

2022-05-30 07:13 UTC, alpanaca commented on solidity/contracts/8.13/nft-staking/NFTBoostedLeverageController.sol
> +    return 0;
```suggestion
    return nftAddress != address(0) ? boostedKillFactors[nftAddress][_worker] : 0;
```

2022-05-30 07:13 UTC, alpanaca commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +    if (_nftAddress == address(0)) revert NFTStaking_InvalidPoolAddress();
do we really need this as it will revert the next line

2022-05-30 07:13 UTC, alpanaca commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +    if (_lockPeriod > poolInfo[_nftAddress].maxLockPeriod) revert NFTStaking_InvalidLockPeriod();
```suggestion
      if (_lockPeriod < poolInfo[_nftAddress].minLockPeriod || _lockPeriod > poolInfo[_nftAddress].maxLockPeriod) revert NFTStaking_InvalidLockPeriod();
```

2022-05-30 07:13 UTC, alpanaca commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +    if (_lockPeriod > poolInfo[_nftAddress].maxLockPeriod) revert NFTStaking_InvalidLockPeriod();
```suggestion
      if (_lockPeriod < poolInfo[_nftAddress].minLockPeriod || _lockPeriod > poolInfo[_nftAddress].maxLockPeriod) revert NFTStaking_InvalidLockPeriod();
```

2022-05-30 07:16 UTC, alpanaca commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +
```suggestion
constructor() initializer {}
```

2022-05-30 07:35 UTC, ricardo-alpaca commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +    if (_nftAddress == address(0)) revert NFTStaking_InvalidPoolAddress();
I'll keep it there to prevent an accidental zero address is added as a pool.

2022-05-30 08:32 UTC, alpanaca submitted a review, later dismissed

2022-05-30 08:56 UTC, alpanaca commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +    if (_nftAddress == address(0)) revert NFTStaking_InvalidPoolAddress();
I mean it will get revert the next line anyway no?

2022-05-30 08:57 UTC, alpanaca commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +    if (_nftAddress == address(0)) revert NFTStaking_InvalidPoolAddress();
And in the add pool you already check for zero address anyway

2022-05-31 03:54 UTC, spicysquid168 commented on solidity/contracts/8.13/nft-staking/NFTBoostedLeverageController.sol
> +  mapping(address => mapping(address => uint256)) public boostedKillFactors;
Theses mapping can be combined to one single slot. You can do
```
struct BoostedConfig {
    uint64 workFactor;
    uint64 killFactor;
}
mapping(address => mapping(address => BoostedConfig)) public boostedConfig;
```
Less storage less access = less gas consumption.

2022-05-31 03:54 UTC, spicysquid168 commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +  struct NFTStakingInfo {
No need this to be struct

2022-05-31 03:54 UTC, spicysquid168 commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +  struct PoolInfo {
This PoolInfo can be optimized in 2 ways:
1. Reduce bits to make it one single slot.
```
struct PoolInfo {
  uint8 isInit;
  uint32 poolWeight;
  uint32 minLockPeriod;
  uint32 maxLockPeriod;
}
```
2. Throw away struct completely and use codec `bytes32` instead. So the mapping would just only be
```
mapping(address => bytes32) public poolInfo;
```
I think codec is better.

2022-05-31 03:54 UTC, spicysquid168 commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +    emit LogStakeNFT(msg.sender, _nftAddress, _nftTokenId, _lockUntil);
emit depositId here as well so subgraph can catch the event and integrate with FE easier

2022-05-31 03:54 UTC, spicysquid168 commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +    emit LogUnstakeNFT(msg.sender, _nftAddress, _nftTokenId);
emit depositId

2022-05-31 03:54 UTC, spicysquid168 commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +    bool isInit;
Enforcing minimum `poolWeight` > 0 would eliminate the need of this storage, then one can check pool existent by if poolWeight == 0.

2022-05-31 03:54 UTC, spicysquid168 commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +    userNFTInStakingPool[msg.sender][_nftAddress] += 1;
Can this be overflown? I think usually 1 collection of NFT is like 10k-100k max. So this can be
```
unchecked {
    userNFTInStakingPool[msg.sender][_nftAddress] += 1;
}
```

2022-05-31 03:54 UTC, spicysquid168 commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +    userStakingNFT[_depositId].lockUntil = _newLockUntil;
Add space to separate Check-Effect-Interaction pattern

2022-05-31 03:54 UTC, spicysquid168 commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +    userNFTInStakingPool[msg.sender][_nftAddress] -= 1;
I think this can also unchecked

2022-05-31 03:54 UTC, spicysquid168 commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +    userHighestWeightNftAddress[msg.sender] = address(0x00);
address(0) would be enough. LOL.

2022-05-31 03:54 UTC, spicysquid168 commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +    for (uint256 i = 0; i < _length; i++) {
```
for (uint256 i = 0; i < _length; ) {
  // do stuffs
  unchecked {
    ++i;
  }
}

2022-05-31 05:11 UTC, ricardo-alpaca commented on solidity/contracts/8.13/nft-staking/NFTStaking.sol
> +  struct PoolInfo {
I'll go with the first option for this one.

2022-05-31 10:07 UTC, ricardo-alpaca commented on solidity/contracts/8.13/nft-staking/NFTBoostedLeverageController.sol
> +  constructor() initializer {}
This is from this recommendation https://blog.trailofbits.com/2020/12/16/breaking-aave-upgradeability/

2022-06-01 04:11 UTC, spicysquid168 approved these changes

2022-06-01 04:11 UTC, merged