[main][feat] delta vault to support executor
alpaca-finance/bsc-alpaca-contract pull request #305
Opened 2022-05-24 08:50 UTC by jakeal-papaca

## Description
 - delta vault to support executor

## Why?

## ChangeLogs:
 - DeltaNeutralVault03
 - DeltaNeutralVaultConfig03

### Link to story (if available)

2022-05-24 08:53 UTC, Alpaca-Cappuccino commented on solidity/contracts/8.10/protocol/DeltaNeutralVaultConfig03.sol
> +  event LogSetExcutor(
LogSetExcutor >>> LogSetExecutor

2022-05-24 08:55 UTC, Alpaca-Cappuccino commented on solidity/contracts/8.10/protocol/DeltaNeutralVaultConfig03.sol
> +  uint256 private constant MAX_MANGEMENT_FEE_PER_SEC = 3170979198;
MANAGEMENT

2022-05-24 09:19 UTC, pana100x commented on solidity/contracts/8.10/protocol/DeltaNeutralVaultConfig03.sol
> +    return false;
👍

2022-05-24 11:17 UTC, alpanaca requested changes

2022-05-24 11:17 UTC, alpanaca commented on solidity/contracts/8.10/protocol/DeltaNeutralVault03.sol
> +    // Perform the actual work, using a new scope to avoid stack-too-deep errors.
Update this comment to the new implementation

2022-05-24 11:17 UTC, alpanaca commented on solidity/contracts/8.10/protocol/DeltaNeutralVault03.sol
> +  function _execute(
We don't use this anymore, do we?

2022-05-27 10:10 UTC, almost-llamas requested changes

2022-05-27 10:10 UTC, almost-llamas commented on solidity/contracts/8.10/protocol/DeltaNeutralVault03.sol
> +    IExecutor(config.withdrawExecutor()).exec(_data);
The executor needs the withdrawing share amount. I suggest packed it into a single byte.
```
    IExecutor(config.withdrawExecutor()).exec(bytes.concat(abi.encode(_shareToWithdraw), _data));

2022-05-27 10:14 UTC, almost-llamas commented on solidity/contracts/8.10/protocol/DeltaNeutralVault03.sol
> +    IExecutor(config.depositExecutor()).exec(_data);
Same situation as withdraw function.
```
    IExecutor(config.withdrawExecutor()).exec(bytes.concat(abi.encode(_stableTokenAmount, _assetTokenAmount), _data));

2022-05-30 06:41 UTC, ricardo-alpaca approved these changes

2022-05-30 06:41 UTC, almost-llamas approved these changes

2022-05-30 07:14 UTC, alpanaca approved these changes

2022-05-31 04:03 UTC, spicysquid168 approved these changes

2022-05-31 06:30 UTC, merged