[main][feat] pancakev2mcv2worker02 support cake as basetoken
alpaca-finance/bsc-alpaca-contract pull request #311
Opened 2022-05-27 04:38 UTC by jr-alpaca

## Description

- Pancakev2mcv2worker02 support cake as baseToken
## Why?

- make reward token to not mixed with supply token
## ChangeLogs:

### Link to story (if available)

2022-05-27 04:49 UTC, alpanaca submitted a review, later dismissed

2022-05-27 05:03 UTC, spicysquid168 requested changes

2022-05-27 05:24 UTC, jr-alpaca commented on solidity/contracts/6/protocol/workers/pcs/PancakeswapV2MCV2Worker02.sol
>      require(
can we just call setReinvestConfig and remove all reinvest config check from initialize?

2022-05-31 04:06 UTC, spicysquid168 approved these changes

2022-05-31 04:08 UTC, almost-llamas approved these changes

2022-05-31 05:12 UTC, ricardo-alpaca approved these changes

2022-05-31 05:22 UTC, merged