[main[feat][alpaca 4463] ausd staking creditor
alpaca-finance/bsc-alpaca-contract pull request #341
Opened 2022-06-27 07:17 UTC by Alpaca-Cappuccino

## Description
AUSD staking creditor

- new contract and test script

Link: ALPACA 4463

2022-06-28 06:41 UTC, jr-alpaca approved these changes

2022-06-28 06:46 UTC, Alpaca-Cappuccino commented on deploy/exec/creditor/deploy/ausd-staking-creditor.ts
> +  const AUSD_STAKING_ADDRESS = "0x201994a052781A133b425E4EB5655541A4DEE081";
already fixed please refresh

2022-06-28 06:46 UTC, Alpaca-Cappuccino commented on deploy/exec/creditor/deploy/ausd-staking-creditor.ts
> +  console.log(">> Deploying an upgradable AUSDStakingCreditor contract");
already fixed please refresh

2022-06-28 10:02 UTC, alpanaca requested changes

2022-06-28 10:02 UTC, alpanaca commented on solidity/contracts/8.13/interfaces/IAUSDStaking.sol
> +  function balanceOfAt(address _user, uint256 _blockNumber) external view returns (uint256);
I don't think we have the balanceOfAt in AIP8.

2022-06-28 10:37 UTC, alpanaca approved these changes

2022-06-29 03:43 UTC, jr-alpaca approved these changes

2022-06-29 03:44 UTC, merged