[main][feat] Automated Vaults Repurchase
alpaca-finance/bsc-alpaca-contract pull request #355
Opened 2022-07-26 07:15 UTC by alpanaca

## Description
New version of DeltaNeutralVault that allow repurchase process.

## Why?
To reduce price impact during rebalancing.

## ChangeLogs:
- new two strats
- delta04.repurchase()
- test files

### Link to story (if available)

2022-07-26 08:22 UTC, alpanaca commented on solidity/contracts/6/protocol/strategies/repurchase/RepurchaseBorrowStrategy.sol
> +import "../../apis/pancake/IPancakeRouter02.sol";
Should remove this

2022-07-26 09:44 UTC, jr-alpaca commented on solidity/contracts/6/protocol/strategies/repurchase/RepurchaseBorrowStrategy.sol
> +  /// @dev Create a new add two-side optimal strategy instance.
```suggestion
  /// @dev Create a new repurchase borrow strategy instance.
```

2022-07-26 11:15 UTC, jr-alpaca commented on solidity/contracts/8.13/DeltaNeutralVault04.sol
> +    );
Token decimals of stable and asset token may not be the same. Should normalize both token amount before calculation.

2022-07-26 11:31 UTC, jr-alpaca commented on solidity/contracts/8.13/DeltaNeutralVault04.sol
> +    if (_amountOut > uint256(_assetExposure >= 0 ? _assetExposure : (_assetExposure * -1)))
_amountOut may be in the form of baseToken which we cannot use to compare with assetExposure.

2022-07-27 15:40 UTC, alpanaca commented
Repurchase should limit to EOA only.

2022-08-01 06:56 UTC, alpanaca commented on solidity/contracts/6/protocol/strategies/repurchase/RepurchaseBorrowStrategy.sol
> +    require(okDeltaNeutralVaults[_deltaNeutralVault], "RepurchaseBorrowStrategy::execute:: bad target");
I think this is a safety net for Executor that compose the input which is out of our scope. Can leave it this way.

2022-08-01 10:30 UTC, jr-alpaca submitted a review, later dismissed

2022-08-10 08:16 UTC, abc-alpaca requested changes

2022-08-10 08:16 UTC, abc-alpaca commented on deploy/exec/strategies/config/set-whitelisted-workers.ts
> +import { HardhatRuntimeEnvironment } from "hardhat/types";
merge logic with `set-whitelisted-workers-timelock`

2022-08-10 08:16 UTC, abc-alpaca commented on package.json
> +    "test:delta04": "forge test --match-contract DeltaNeutralVault04"
need command like this
```
"deploy:mainnet:strategies:config:set-whitelisted-delta" : "hardhat --network mainnet deploy --no-compile --reset --tags SetSharedStratsWhitelistedDeltaNeutralVaults",
"deploy:mainnet:strategies:config:set-whitelisted-worker" : "hardhat --network mainnet deploy --no-compile --reset --tags SetSharedStratsWhitelistedWorkers",
"deploy:mainnet:strategies:deploy:repurchase-borrow":  : "hardhat --network mainnet deploy --no-compile --reset --tags RepurchaseBorrowStrategies",
"deploy:mainnet:strategies:deploy:repurchase-repay":  : "hardhat --network mainnet deploy --no-compile --reset --tags RepurchaseRepayStrategies",

```

2022-08-10 08:28 UTC, sora-alpaca submitted a review, later dismissed

2022-08-22 05:05 UTC, abc-alpaca requested changes

2022-08-22 05:16 UTC, jr-alpaca approved these changes

2022-08-22 05:16 UTC, ricardo-alpaca submitted a review, later dismissed

2022-08-22 05:21 UTC, almost-llamas approved these changes

2022-08-22 05:21 UTC, jr-alpaca approved these changes

2022-08-22 05:22 UTC, merged