[main][feat] Integrate Binance oracle
alpaca-finance/bsc-alpaca-contract pull request #370
Opened 2022-09-21 06:47 UTC by spicysquid168

## Description
Integrate Binance Oracle to Oracle Medianizer

## Why?
Increase oracle robustness

2022-09-21 07:34 UTC, jr-alpaca commented on solidity/contracts/8.11/protocol/price-oracle/BinancePriceOracle.sol
> +        (, _answer2, , _lastUpdate2, ) = priceFeeds[token0][token1][1].latestRoundData();
what value does _answer2 return?

2022-09-21 07:42 UTC, spicysquid168 commented on solidity/contracts/8.11/protocol/price-oracle/BinancePriceOracle.sol
> +        (, _answer2, , _lastUpdate2, ) = priceFeeds[token0][token1][1].latestRoundData();
Should be the same denomination as `_answer1`
For example if we would like to add ETHBTC to BinancePriceOracle. We can do it by adding:
ETH price feeds = [[ETHUSD], [BTC,USD]]
ETHUSD -> Denomination is USD. This is `_answer1`
BTCUSD -> Denomination is USD. This is `_answer2`

2022-09-21 08:37 UTC, abc-alpaca requested changes

2022-09-21 08:37 UTC, abc-alpaca commented on hardhat.config.ts
> +      url: "https://rpc.tenderly.co/fork/917c151c-d3bc-4e15-b339-edb69c7e728f/",
```suggestion
      url: process.env.BSC_TESTNET_RPC || 
      "https://data-seed-prebsc-1-s1.binance.org:8545/",
```
is it better to put on env?

2022-09-21 11:32 UTC, jr-alpaca commented on solidity/contracts/8.11/protocol/price-oracle/BinancePriceOracle.sol
> +        (, _answer2, , _lastUpdate2, ) = priceFeeds[token0][token1][1].latestRoundData();
Does this mean if the priceFeedCount has only 1 source which is [ETH,USD], but we want to get price for ETHBTC. It will return ETHUSD price.

2022-09-23 03:41 UTC, spicysquid168 commented on solidity/contracts/8.11/protocol/price-oracle/BinancePriceOracle.sol
> +        (, _answer2, , _lastUpdate2, ) = priceFeeds[token0][token1][1].latestRoundData();
That is correct. But that should falls into mis-config. Cannot help with that.

2022-09-23 04:15 UTC, jr-alpaca approved these changes

2022-09-23 04:29 UTC, abc-alpaca approved these changes

2022-09-26 04:08 UTC, merged