[main][feat] AV migration
alpaca-finance/bsc-alpaca-contract pull request #376
Opened 2022-11-16 04:27 UTC by 69alpacas

## Description

## Why?

## ChangeLogs:

### Link to story (if available)

2022-11-16 04:35 UTC, alpanaca requested changes

2022-11-16 04:35 UTC, alpanaca commented on solidity/contracts/8.13/AVMigration.sol
> +import { console } from "solidity/tests/utils/console.sol";
```suggestion
```

2022-11-16 04:35 UTC, alpanaca commented on solidity/contracts/8.13/AVMigration.sol
> +  constructor() {}
```suggestion
```

2022-11-16 04:35 UTC, alpanaca commented on solidity/contracts/8.13/AVMigration.sol
> +    require(dstVault != address(0), "destination vault does not exist");
Use the custom error instead of require

2022-11-16 04:35 UTC, alpanaca commented on solidity/tests/protocol/av-migration/AVMigration.t.sol
> +  function testFail_notOwnerSetMigrationPaths() external {
```suggestion
  function testRevert_WhenCallerIsNotOwner_SetMigrationPathsShouldRevert() external {
```

2022-11-16 04:37 UTC, alpanaca commented on solidity/contracts/8.13/AVMigration.sol
> +  event LogMigration(address indexed _shareOwner, uint256 _sharesFromSrc, uint256 _sharesToDst);
Better add sourceAddr and destinationAddr

2022-11-16 04:57 UTC, alpanaca submitted a review, later dismissed

2022-11-16 05:05 UTC, abc-alpaca approved these changes

2022-11-16 09:00 UTC, abc-alpaca submitted a review, later dismissed

2022-11-16 10:09 UTC, alpanaca submitted a review, later dismissed

2022-11-17 09:17 UTC, jr-alpaca commented on solidity/contracts/8.13/AVMigration.sol
> +  ) public {
please put onlyEOAorWhitelisted modifier
```suggestion
  ) public onlyEOAorWhitelisted{
```

2022-11-17 09:36 UTC, jr-alpaca commented on solidity/contracts/8.13/AVMigration.sol
> +import "solidity/contracts/8.13/utils/Ownable.sol";
use relative import path for format consistency

2022-11-18 04:49 UTC, alpanaca requested changes

2022-11-18 04:49 UTC, alpanaca commented on solidity/contracts/8.13/AVMigration.sol
> +      abi.encode(0)
should send two uint256 here

2022-11-18 04:49 UTC, alpanaca commented on solidity/contracts/8.13/AVMigration.sol
> +      abi.encode(0)
should send two uint256 here

2022-11-23 05:58 UTC, alpanaca approved these changes

2022-12-09 06:29 UTC, jr-alpaca approved these changes

2022-12-09 06:29 UTC, alpanaca approved these changes

2022-12-09 06:29 UTC, merged