[Main][Feat][alpaca-949] Single asset partial close liquidate strategy
alpaca-finance/bsc-alpaca-contract pull request #70
Opened 2021-06-25 03:33 UTC by jr-alpaca

## Description

Develop a new strategy for support partial close in single asset pool
## Why?

users want to be able to partially close their position in single asset pool
## ChangeLogs:

new strategy partial close liquidation for single asset
deployment script
unit test

### Link to story (if available)

2021-06-25 04:48 UTC, abraham-alpaca commented on contracts/6/protocol/strategies/pancakeswapV2-restricted-single-asset/PancakeswapV2RestrictedSingleAssetStrategyPartialCloseLiquidate.sol
> +    // 5. Reset approval for safety reason
sending farmingToken back as well since you convert `portion` of farmingToken, thus some farmingToken will remain

2021-06-25 04:51 UTC, abraham-alpaca commented on test/PancakeswapV2_Restricted_SingleAsset_StrategyPartialCloseLiquidate.test.ts
> +      const aliceBalanceBefore = await wbnb.balanceOf(await alice.getAddress())
says aliceBalanceBefore = 50 WBNB
alice want to liquidate 0.04 farmingToken back to wbnb
// if 0.1 FToken = 1 WBNB
// 0.04 FToken will be (0.1 * 0.9975) * (1 / (0.1 + 0.04 * 0.9975)) = 0.2852037169406719 WBNB
alice should get 50 + 0.2852037169406719 WBNB
worker should get  0.06 WBNB

2021-06-25 04:55 UTC, abraham-alpaca commented on test/PancakeswapV2_Restricted_SingleAsset_StrategyPartialCloseLiquidate.test.ts
> +      const aliceBalanceBefore = await baseToken.balanceOf(await alice.getAddress())
if 0.1 FToken = 1 WBNB
0.04 FToken will be (0.1 * 0.9975) * (1 / (0.1 + 0.04 * 0.9975)) = 0.2852037169406719 WBNB

if 1 WBNB = 1 BaseToken
0.2852037169406719 WBNB = (0.2852037169406719* 0.9975) * (1 / (1 + 0.2852037169406719 * 0.9975)) = 0.22148132793360054 BaseToken
thus alice should get 100 - 1(from providing a liquidity) (99 + 0.22148132793360054) =  99.2214813279336 BaseToken

2021-06-25 05:44 UTC, jr-alpaca commented on test/PancakeswapV2_Restricted_SingleAsset_StrategyPartialCloseLiquidate.test.ts
> +      const aliceBalanceBefore = await wbnb.balanceOf(await alice.getAddress())
(0.04 * 0.9975) * (1 / (0.1 + 0.04 * 0.9975))

2021-06-29 04:26 UTC, ricardo-alpaca approved these changes
Looks good to me.

2021-06-30 06:19 UTC, ricardo-alpaca commented on contracts/6/protocol/strategies/pancakeswapV2-restricted-single-asset/PancakeswapV2RestrictedSingleAssetStrategyPartialCloseLiquidate.sol
> +    farmingToken.safeApprove(address(router), 0);
Please add event emission and unit test for that.

2021-07-01 10:18 UTC, spicysquid168 requested changes

2021-07-01 10:18 UTC, spicysquid168 commented on contracts/6/protocol/strategies/pancakeswapV2-restricted-single-asset/PancakeswapV2RestrictedSingleAssetStrategyPartialCloseLiquidate.sol
> +    (uint256 minBaseTokenAmount, uint256 farmingTokenToLiquidate, uint256 toRepaidBaseTokenDebt) =
reorder
- farmingTokenToLiquidate
- toRepaidBaseTokenDebt
- minBaseTokenAmount

2021-07-01 10:18 UTC, spicysquid168 commented on contracts/6/protocol/strategies/pancakeswapV2-restricted-single-asset/PancakeswapV2RestrictedSingleAssetStrategyPartialCloseLiquidate.sol
> +    // 1. minBaseTokenAmount for validating a baseToken amount from a conversion of a farmingToken.
Update comment. Something like:
1. Decode params from user
- farmingTokenToLiquidate - How much farmingToken to liquidate?
- toRepaidBaseTokenDebt - How much the user wants to repaid the debt?
- minBaseTokenAmount - For validating slippage

2021-07-01 10:18 UTC, spicysquid168 commented on test/PancakeswapV2_Restricted_SingleAsset_StrategyPartialCloseLiquidate.test.ts
> +          // Alice uses Partial Close Liquidate strategy yet again, but now with an unreasonable minFarmingTokenAmount request
Update comment here. Alice not uses Partial Close Liquidate strategy yet again -> she just use it for the first time

2021-07-01 10:18 UTC, spicysquid168 commented on test/PancakeswapV2_Restricted_SingleAsset_StrategyPartialCloseLiquidate.test.ts
> +      )).to.emit(strat, 'PancakeswapV2RestrictedSingleAssetStrategyPartialCloseLiquidate');
assert args too

2021-07-02 08:49 UTC, spicysquid168 requested changes

2021-07-02 08:49 UTC, spicysquid168 commented on contracts/6/protocol/strategies/pancakeswapV2-restricted-single-asset/PancakeswapV2RestrictedSingleAssetStrategyPartialCloseLiquidate.sol
> +      abi.decode(data, (uint256, uint256, uint256));
add require(toRepaidBaseTokenDebt <= debt)

2021-07-02 08:49 UTC, spicysquid168 commented on contracts/6/protocol/strategies/pancakeswapV2-restricted-single-asset/PancakeswapV2RestrictedSingleAssetStrategyPartialCloseLiquidate.sol
> +      toRepaidBaseTokenDebt
remove this out

2021-07-07 08:54 UTC, spicysquid168 commented on test/CakeMaxiWorker.test.ts
> +          // worker will get a base token based on 0.008315964985410587 FTOKEN to liquidate will get 0.108595436223603774 baseToken
where does this come from `0.108595436223603774`?

2021-07-07 08:54 UTC, spicysquid168 commented on test/CakeMaxiWorker.test.ts
> +          expect(aliceFarmingTokenAfter.sub(aliceFarmingTokenBefore)).to.eq(ethers.utils.parseEther('0'))
please assert alice's debt after she did partial close too.

2021-07-07 09:03 UTC, jr-alpaca commented on test/CakeMaxiWorker.test.ts
> +          // worker will get a base token based on 0.008315964985410587 FTOKEN to liquidate will get 0.108595436223603774 baseToken
from the amount of FTOKEN that Alice want to liquidate.
swap 0.008315964985410587 FTOKEN will turn to 0.108595436223603774 baseToken.

2021-07-07 12:08 UTC, spicysquid168 approved these changes

2021-07-07 12:12 UTC, sundayalpaca approved these changes

2021-07-08 03:35 UTC, merged