[main][feat]pancakeswap v2 restricted strategy partial close minimize trading
alpaca-finance/bsc-alpaca-contract pull request #72
Opened 2021-06-28 10:19 UTC by jakeal-papaca

## Description
 - pancake swap V2 restricted strategy partial close minimize trading contract
 - deployment script

## Why?
users want to have an option to partially close their position, payback their debt, and minimize trading

2021-06-29 04:03 UTC, almost-llamas commented on contracts/6/protocol/strategies/pancakeswapV2-restricted/PancakeswapV2RestrictedStrategyPartialCloseMinimizeTrading.sol
> +    // 3. Remove all liquidity back to BaseToken and farming tokens.
inconsistent case `BaseToken and farming tokens.`

2021-06-29 04:05 UTC, almost-llamas commented on contracts/6/protocol/strategies/pancakeswapV2-restricted/PancakeswapV2RestrictedStrategyPartialCloseMinimizeTrading.sol
> +    farmingToken.safeApprove(address(router), uint256(-1));
Why don't we handle these two line the same way, are there any particular reason?

2021-06-29 04:11 UTC, almost-llamas commented on contracts/6/protocol/strategies/pancakeswapV2-restricted/PancakeswapV2RestrictedStrategyPartialCloseMinimizeTrading.sol
> +      }
This can be optimized var declaration a bit i guess
```
      uint256 farmingTokenbalance = farmingToken.myBalance();
      uint256 remainingDebt = toBeRepaidBaseTokenDebt.sub(baseToken.myBalance());
      if (remainingDebt > 0) {
        // Convert some farming tokens to BaseToken.
        uint256[] memory amounts = router.getAmountsIn(remainingDebt, path);
        
        // the rest remain the same ...
      }
```

2021-06-29 04:13 UTC, almost-llamas commented on contracts/6/protocol/strategies/pancakeswapV2-restricted/PancakeswapV2RestrictedStrategyPartialCloseMinimizeTrading.sol
> +      baseToken.safeTransfer(msg.sender, remainingBalance);
Save var declaration
```
      baseToken.safeTransfer(msg.sender, baseToken.myBalance());

2021-06-29 04:28 UTC, ricardo-alpaca requested changes
There are some minor inconsistencies but the logic looks fine to me. Please discuss with the other alpaca to resolve them. 頑張ってね

2021-06-29 04:28 UTC, ricardo-alpaca commented on contracts/6/protocol/strategies/pancakeswapV2-restricted/PancakeswapV2RestrictedStrategyPartialCloseMinimizeTrading.sol
> +          amounts[0] <= farmingTokenbalance,
In Single Asset Minimize Trading Strategy, the check is 
``require(farmingTokenToLiquidate > farmingTokenToBeRepaidDebts[0], "PancakeswapV2RestrictedSingleAssetStrategyPartialCloseWithdrawMinimizeTrading::execute:: not enough to pay back debt");``.
https://github.com/alpaca-finance/bsc-alpaca-contract/pull/73/files
I think we should be consistent on how we write this as it is doing the same thing.
Please discuss with @sundayalpaca

2021-06-29 04:28 UTC, ricardo-alpaca commented on contracts/6/protocol/strategies/pancakeswapV2-restricted/PancakeswapV2RestrictedStrategyPartialCloseMinimizeTrading.sol
> +    (uint256 lpTokenToLiquidate, uint256 toBeRepaidBaseTokenDebt, uint256 minFarmingToken) =
In Single Asset Minimize Trading Strategy, ``toBeRepaidBaseTokenDebt`` is called ``toRepaidBaseTokenDebt`` and the order of the inputs is different. Please discuss with @sundayalpaca and make them consistent.

2021-07-01 03:36 UTC, ricardo-alpaca submitted a review, later dismissed

2021-07-01 10:00 UTC, spicysquid168 requested changes

2021-07-01 10:00 UTC, spicysquid168 commented on test/PancakeswapV2_Restricted_StrategyPartialCloseMinimizeTrading.test.ts
> +      // Bob's position: 40 farming token + 2 base token (8.944271909999158785 LP token)
I don't think that we need comment here

2021-07-01 10:00 UTC, spicysquid168 commented on contracts/6/protocol/strategies/pancakeswapV2-restricted/PancakeswapV2RestrictedStrategyPartialCloseMinimizeTrading.sol
> +    uint256 remainingFarmingToken = farmingToken.myBalance();
Should return remaining LPs back to msg.sender (Worker).

2021-07-01 10:12 UTC, spicysquid168 requested changes

2021-07-01 10:12 UTC, spicysquid168 commented on test/PancakeswapV2_Restricted_StrategyPartialCloseMinimizeTrading.test.ts
> +          expect(await lpV2.balanceOf(strat.address)).to.be.bignumber.eq(
should not have any LP left in strategy

2021-07-02 08:49 UTC, spicysquid168 requested changes

2021-07-02 08:49 UTC, spicysquid168 commented on contracts/6/protocol/strategies/pancakeswapV2-restricted/PancakeswapV2RestrictedStrategyPartialCloseMinimizeTrading.sol
> +    IPancakePair lpToken = IPancakePair(factory.getPair(farmingToken, baseToken));
add require(toRepaidBaseTokenDebt <= debt)

2021-07-08 10:24 UTC, spicysquid168 requested changes

2021-07-08 10:24 UTC, spicysquid168 commented on contracts/6/protocol/strategies/pancakeswapV2-restricted/PancakeswapV2RestrictedStrategyPartialCloseMinimizeTrading.sol
> +    require(
Can do something like `address(lpToken).safeTransfer(..)`

2021-07-08 10:24 UTC, spicysquid168 commented on test/Vault_PancakeswapV2.test.ts
> +        // Bob closes position with maxReturn 5,000,000,000 and liquidate half of his position
please change from 5,000,000,000 to 5 BTOKEN

2021-07-08 10:24 UTC, spicysquid168 commented on test/Vault_PancakeswapV2.test.ts
> +        // - Bob's position debt must be 0
Bob's position debt must be 5 BTOKEN as he return only 5 BTOKEN. His position was 20 BTOKEN (10 from his pocket + 10 from Vault)

2021-07-09 02:45 UTC, spicysquid168 requested changes

2021-07-09 02:45 UTC, spicysquid168 commented on contracts/6/protocol/strategies/pancakeswapV2-restricted/PancakeswapV2RestrictedStrategyPartialCloseMinimizeTrading.sol
> +      lpToken.approve(address(router), uint256(-1)),
change this to `address(lpToken).safeApprove(...)` too

2021-07-09 04:31 UTC, spicysquid168 approved these changes

2021-07-09 04:44 UTC, ricardo-alpaca approved these changes

2021-07-09 05:10 UTC, merged