feat: add contract single asset  partial close withdraw minimize trai…
alpaca-finance/bsc-alpaca-contract pull request #73
Opened 2021-06-28 12:56 UTC by sundayalpaca

…ning

## Description
feat: add contract single asset  partial close withdraw minimize trai…

2021-06-29 03:44 UTC, slowcheetah69 commented on contracts/6/protocol/strategies/pancakeswapV2-restricted-single-asset/PancakeswapV2RestrictedSingleAssetStrategyPartialCloseWithdrawMinimizeTrading.sol
> +    uint256 farmingTokenBalance = farmingToken.myBalance();
The farmingToken balance should be checked here if it is enough to pay back the debt.
```suggestion
require(
      farmingToken.myBalance() >= farmingTokenToLiquidate,
      "PancakeswapV2RestrictedSingleAssetStrategyPartialCloseLiquidate::execute:: insufficient farmingToken received from worker"
    );
```
see https://github.com/alpaca-finance/bsc-alpaca-contract/pull/70/files

2021-06-29 03:49 UTC, ricardo-alpaca commented on contracts/6/protocol/strategies/pancakeswapV2-restricted-single-asset/PancakeswapV2RestrictedSingleAssetStrategyPartialCloseWithdrawMinimizeTrading.sol
> +        require(farmingTokenToLiquidate > farmingTokenToBeRepaidDebts[0], "PancakeswapV2RestrictedSingleAssetStrategyPartialCloseWithdrawMinimizeTrading::execute:: not enough to pay back debt");
What if ``farmingTokenToLiquidate == farmingTokenToBeRepaidDebts[0]``?
Should we allow it to pass?

2021-06-29 04:28 UTC, ricardo-alpaca requested changes
There are some minor inconsistencies and one questionable check. Please discuss with the other alpaca to resolve them.

2021-06-29 04:28 UTC, ricardo-alpaca commented on contracts/6/protocol/strategies/pancakeswapV2-restricted-single-asset/PancakeswapV2RestrictedSingleAssetStrategyPartialCloseWithdrawMinimizeTrading.sol
> +  address public wNative;
In ``PancakeswapV2RestrictedSingleAssetStrategyWithdrawMinimizeTrading.sol``, this variable was declared as
``IWETH public wbnb;`` which seems better to me as it is defined as IWETH type. However, ``PancakeswapV2RestrictedSingleAssetStrategyWithdrawMinimizeTrading.sol`` also used ``address public wNative;``. Perhaps we could be more consistent on this. Try discussing with @abraham-alpaca on this.

2021-06-30 08:05 UTC, ricardo-alpaca commented on contracts/6/protocol/strategies/pancakeswapV2-restricted-single-asset/PancakeswapV2RestrictedSingleAssetStrategyPartialCloseWithdrawMinimizeTrading.sol
> +  event PancakeswapV2RestrictedSingleAssetStrategyPartialCloseWithdrawMinimizeTrading(
Change event name to `PancakeswapV2RestrictedSingleAssetStrategyPartialCloseWithdrawMinimizeTradingEvent`

2021-07-01 03:35 UTC, ricardo-alpaca approved these changes

2021-07-01 09:50 UTC, spicysquid168 requested changes

2021-07-01 09:50 UTC, spicysquid168 commented on contracts/6/protocol/strategies/pancakeswapV2-restricted-single-asset/PancakeswapV2RestrictedSingleAssetStrategyPartialCloseWithdrawMinimizeTrading.sol
> +import "hardhat/console.sol";
remove hardhat/console.sol please

2021-07-01 09:50 UTC, spicysquid168 commented on contracts/6/protocol/strategies/pancakeswapV2-restricted-single-asset/PancakeswapV2RestrictedSingleAssetStrategyPartialCloseWithdrawMinimizeTrading.sol
> +    require(okWorkers[msg.sender], "PancakeswapV2RestrictedSingleAssetStrategyPartialCloseWithdrawMinimizeTrading::onlyWhitelistedWorkers:: bad worker");
setup solhint/lint

2021-07-01 09:50 UTC, spicysquid168 commented on contracts/6/protocol/strategies/pancakeswapV2-restricted-single-asset/PancakeswapV2RestrictedSingleAssetStrategyPartialCloseWithdrawMinimizeTrading.sol
> +      uint256 minFarmingTokenAmount,
reorder the variables.
- farmingTokenToLiquidate
- toRepaidBaseTokenDebt
- minFarmingTokenAmount

2021-07-01 09:50 UTC, spicysquid168 commented on contracts/6/protocol/strategies/pancakeswapV2-restricted-single-asset/PancakeswapV2RestrictedSingleAssetStrategyPartialCloseWithdrawMinimizeTrading.sol
> +    // 1. minFarmingTokenAmount for validating a farmingToken amount after leaving the stake.
Update comment here

2021-07-01 09:50 UTC, spicysquid168 commented on contracts/6/protocol/strategies/pancakeswapV2-restricted-single-asset/PancakeswapV2RestrictedSingleAssetStrategyPartialCloseWithdrawMinimizeTrading.sol
> +    if (toRepaidBaseTokenDebt > 0) {
add comment above this step for readability

2021-07-01 10:10 UTC, spicysquid168 requested changes

2021-07-01 10:10 UTC, spicysquid168 commented on contracts/6/protocol/strategies/pancakeswapV2-restricted-single-asset/PancakeswapV2RestrictedSingleAssetStrategyPartialCloseWithdrawMinimizeTrading.sol
> +    uint256 lpTokenToLiquidate = 0;
do we need it here? I think we don't need this variable here.

2021-07-01 10:10 UTC, spicysquid168 commented on contracts/6/protocol/strategies/pancakeswapV2-restricted-single-asset/PancakeswapV2RestrictedSingleAssetStrategyPartialCloseWithdrawMinimizeTrading.sol
> +      lpTokenToLiquidate,
Should be `farmingTokenToLiquidate`

2021-07-01 10:10 UTC, spicysquid168 commented on contracts/6/protocol/strategies/pancakeswapV2-restricted-single-asset/PancakeswapV2RestrictedSingleAssetStrategyPartialCloseWithdrawMinimizeTrading.sol
> +    // 6. Reset approval for safety reason
need to transfer `farmingToken.safeTransfer(farmingTokenBalance.sub(farmingTokenToRepaidDebt))` back to worker to return the leftover amount from partial close

2021-07-02 08:49 UTC, spicysquid168 requested changes

2021-07-02 08:49 UTC, spicysquid168 commented on contracts/6/protocol/strategies/pancakeswapV2-restricted-single-asset/PancakeswapV2RestrictedSingleAssetStrategyPartialCloseWithdrawMinimizeTrading.sol
> +    ) = abi.decode(data, (uint256, uint256, uint256));
add require(toRepaidBaseTokenDebt <= debt)

2021-07-07 12:00 UTC, spicysquid168 submitted a review, later dismissed

2021-07-07 12:54 UTC, almost-llamas submitted a review, later dismissed

2021-07-08 10:12 UTC, spicysquid168 requested changes

2021-07-08 10:12 UTC, spicysquid168 commented on test/CakeMaxiWorker.test.ts
> +        // Alice call minimize trading strategy to close her position
Add more context here. How much Alice wish to close position? How much she repay the debt? etc.

2021-07-08 10:12 UTC, spicysquid168 commented on test/CakeMaxiWorker.test.ts
> +        // x FTOKEN = (x * 0.9975 * 1.1) / (0.09092975676290066 + (x * 0.9975)) = 0.05 WBNB
where does 0.05 WBNB comes from? Can you elaborate the math more in the comment? i.e. Finding how much 0.05WBNB worth in FTOKEN: equation

2021-07-08 10:12 UTC, spicysquid168 commented on test/CakeMaxiWorker.test.ts
> +        // x = 0.0016881046461134437
same here. Elaborate more. Something like Finding how many FTOKEN needed to enough to pay 0.02 debt: equation

2021-07-09 04:25 UTC, spicysquid168 requested changes

2021-07-09 04:25 UTC, spicysquid168 commented on test/CakeMaxiWorker.test.ts
> +        // alice want to repaid bedt only 0.02 BToken
debt

2021-07-09 04:25 UTC, spicysquid168 commented on test/CakeMaxiWorker.test.ts
> +        // if Alice bedt's is 50% of her position which is 0.1 wbnb
debt

2021-07-09 04:25 UTC, spicysquid168 commented on test/CakeMaxiWorker.test.ts
> +        // if Alice bedt's is 50% of her position which is 0.1 wbnb
Alice has 0.05 WBNB as debt. Finding how much 0.05 WBNB worth in FTOKEN:
Equation..

2021-07-09 06:00 UTC, spicysquid168 approved these changes

2021-07-09 06:03 UTC, almost-llamas approved these changes

2021-07-09 06:05 UTC, merged