[main][feat] optimized workers
alpaca-finance/bsc-alpaca-contract pull request #75
Opened 2021-06-29 12:06 UTC by caramel-macchiato-kub

## Description
This is a feature PR for improving reinvestment abilities for 3 workers, with separated contracts and separated test cases from the previous version of workers

2021-06-30 03:51 UTC, ricardo-alpaca commented on contracts/6/protocol/workers/pcs/PancakeswapV2Worker02.sol
> +    uint256 bounty = reward.mul(_treasuryBountyBps) / 10000;
Will there be a case where `_treasuryBountyBps` is not set?

2021-06-30 03:52 UTC, ricardo-alpaca commented on contracts/6/protocol/workers/pcs/PancakeswapV2Worker02.sol
> +    uint256 bounty = reward.mul(_treasuryBountyBps) / 10000;
Oh I've seen the check for this in `work` now.

2021-06-30 04:42 UTC, spicysquid168 commented on contracts/6/protocol/workers/single-asset/CakeMaxiWorker02.sol
> +  event SetTreasuryBountyBps(address indexed account, uint256 bountyBps);
move event up above

2021-06-30 04:42 UTC, spicysquid168 commented on contracts/6/protocol/workers/single-asset/CakeMaxiWorker02.sol
> +  /// thus the actualBaseTokenBalance exists to differentiate an actual base token balance balance without taking to buy back amount into account
without taking buy back amount into account

2021-06-30 04:42 UTC, spicysquid168 commented on contracts/6/protocol/workers/pcs/PancakeswapV2Worker02.sol
> +    uint256 reward = cake.balanceOf(address(this));
if baseToken is $CAKE, then this will included the caller's $CAKE balance as a reward too

2021-06-30 04:42 UTC, spicysquid168 commented on contracts/6/protocol/workers/pcs/PancakeswapV2Worker02.sol
> +    // 3. Send the reward bounty to the caller.
send the reward bounty to _treasuryAccount

2021-06-30 04:42 UTC, spicysquid168 commented on contracts/6/protocol/workers/pcs/PancakeswapV2Worker02.sol
> +    // 6. Mint more LP tokens and stake them for more rewards.
no mint LP here. At this step just stake LPs for more rewards

2021-06-30 04:42 UTC, spicysquid168 commented on contracts/6/protocol/workers/single-asset/CakeMaxiWorker02.sol
> +    // since beneficial vault is the same as the calling vuault, it will think of this reward as a `back` amount to paydebt/ sending back to a position owner
vuault -> vault

2021-06-30 04:42 UTC, spicysquid168 commented on contracts/6/protocol/workers/waultswap/WaultSwapWorker02.sol
> +  event SetTreasuryBountyBps(address indexed account, uint256 bountyBps);
move up

2021-06-30 04:42 UTC, spicysquid168 commented on contracts/6/protocol/workers/waultswap/WaultSwapWorker02.sol
> +    uint256 reward = wex.balanceOf(address(this));
what if baseToken is $WEX

2021-06-30 04:42 UTC, spicysquid168 commented on deploy/s026_upgrade_workers_02.ts
> +    const workers = vault.workers.map((worker) => {
need to escape BETH-ETH PancakeswapWorker

2021-06-30 04:42 UTC, spicysquid168 commented on deploy/s026_upgrade_workers_02.ts
> +    const preparedNewWorker = await upgrades.prepareUpgrade(TO_BE_UPGRADE_WORKERS[i].ADDRESS, TO_BE_UPGRADE_WORKERS[i].FACTORY)
shouldn't prepareUpgrade each worker because it will deploy new implementation every time which make version management harder.

2021-06-30 04:42 UTC, spicysquid168 commented on deploy/s026_upgrade_workers_02.ts
> +    const workers = vault.workers.map((worker) => {
Make it to get an input from deployer not just all workers

2021-06-30 04:42 UTC, spicysquid168 commented on deploy/s027_timelock_add_treasury_fields_workers_02.ts
> +    const workers = vault.workers.map((worker) => {
received worker list from deployer. not all worker.

2021-06-30 04:42 UTC, spicysquid168 commented on deploy/s026_upgrade_workers_02.ts
> +    const workers = vault.workers.map((worker) => {
also make a clear separation between deployer's input and derived variables from config. Can just remove TIMELOCK, PROXY_ADMIN out from input section

2021-06-30 04:42 UTC, spicysquid168 commented on deploy/s027_timelock_add_treasury_fields_workers_02.ts
> +  for(let i = 0; i < TO_BE_UPGRADE_WORKERS.length; i++) {
do it in the same loop, so the deployer gets timelock in pair

2021-06-30 05:38 UTC, ricardo-alpaca commented on contracts/6/protocol/workers/pcs/PancakeswapV2Worker02.sol
> +    _reinvest(treasuryAccount, treasuryBountyBps, baseToken.myBalance());
Don't use `baseToken.myBalance()` here to handle CAKE as base token.

2021-06-30 05:51 UTC, ricardo-alpaca commented on contracts/6/protocol/workers/single-asset/CakeMaxiWorker02.sol
> +    uint256 wad = baseToken.myBalance();
Should this use `actualBaseTokenBalance()`?

2021-06-30 06:18 UTC, abraham-alpaca commented on contracts/6/protocol/workers/pcs/PancakeswapV2Worker02.sol
> +    uint256 reward = cake.balanceOf(address(this));
will require that base != cake at the initial

2021-06-30 06:18 UTC, abraham-alpaca commented on contracts/6/protocol/workers/waultswap/WaultSwapWorker02.sol
> +    uint256 reward = wex.balanceOf(address(this));
will require that base != cake at the initial

2021-06-30 06:18 UTC, abraham-alpaca commented on contracts/6/protocol/workers/pcs/PancakeswapV2Worker02.sol
> +    _reinvest(treasuryAccount, treasuryBountyBps, baseToken.myBalance());
will require that base != cake at the initial

2021-06-30 07:18 UTC, spicysquid168 requested changes

2021-06-30 07:18 UTC, spicysquid168 commented on test/CakeMaxiWorker02.test.ts
> +          // thus, alice we get a bounty of 00018
should be eve would get a bounty of 0.00018 CAKE

2021-06-30 07:18 UTC, spicysquid168 commented on test/CakeMaxiWorker02.test.ts
> +        expect(await (await integratedCakeMaxiWorker.shareToBalance(await integratedCakeMaxiWorker.shares(1)))).to.eq(ethers.utils.parseEther('0.115646280101600954'))
await integratedCakeMaxiWorker.shareToBalance(await integratedCakeMaxiWorker.shares(1))

2021-06-30 07:18 UTC, spicysquid168 commented on test/CakeMaxiWorker02.test.ts
> +            // PancakeswapWorker needs to be updated to PancakeswapV2WorkerMigrate
Upgrade from CakeMaxiWorker to CakeMaxiWorker02 for optimized reinvest

2021-07-07 11:27 UTC, almost-llamas commented on contracts/6/protocol/workers/single-asset/CakeMaxiWorker02.sol
> +    if (treasuryAccount == address(0)) treasuryAccount = address(0xC44f82b07Ab3E691F826951a6E335E1bC1bB0B51);
Should we have this check in `_reinvest` func instead, as there is a small chance we `reinvest` got called too before treasuryAccount is defined properly

2021-07-07 11:31 UTC, almost-llamas commented on contracts/6/protocol/workers/single-asset/CakeMaxiWorker02.sol
> +    uint256 wad = actualBaseTokenBalance();
`wad` should we rename this var?

2021-07-07 11:34 UTC, almost-llamas commented on contracts/6/protocol/workers/single-asset/CakeMaxiWorker02.sol
> +    if (treasuryAccount == address(0)) treasuryAccount = address(0xC44f82b07Ab3E691F826951a6E335E1bC1bB0B51);
resolved due to treasuryAccount is injected to `_reinvest` as param

2021-07-07 11:37 UTC, almost-llamas commented on contracts/6/protocol/workers/single-asset/CakeMaxiWorker02.sol
> +    _reinvest(treasuryAccount, treasuryBountyBps);
Or we just don't reinvest if we the transferAccount is not ready
```
if (treasuryAccount != address(0) && treasuryBountyBps != 0) _reinvest(treasuryAccount, treasuryBountyBps);

2021-07-07 12:16 UTC, spicysquid168 commented on contracts/6/protocol/workers/single-asset/CakeMaxiWorker02.sol
> +    _reinvest(treasuryAccount, treasuryBountyBps);
This is better.

2021-07-09 03:26 UTC, almost-llamas submitted a review, later dismissed

2021-07-09 04:28 UTC, mint-chocolate-frappuccino approved these changes

2021-07-09 05:05 UTC, abraham-alpaca approved these changes

2021-07-09 05:10 UTC, sundayalpaca approved these changes

2021-07-09 05:11 UTC, spicysquid168 approved these changes

2021-07-09 05:12 UTC, merged