[feat]wault swap restricted strategy partial close minimize trading
alpaca-finance/bsc-alpaca-contract pull request #76
Opened 2021-06-30 08:09 UTC by jakeal-papaca

## Description
 - wault swap restricted strategy partial close minimize trading contract
 - deployment script

## Why?
users want to have an option to partially close their position, payback their debt, and minimize trading

2021-06-30 11:04 UTC, ricardo-alpaca submitted a review, later dismissed

2021-07-01 09:35 UTC, spicysquid168 approved these changes

2021-07-01 10:00 UTC, spicysquid168 requested changes

2021-07-01 10:00 UTC, spicysquid168 commented on contracts/6/protocol/strategies/waultswap-restricted/WaultSwapRestrictedStrategyPartialCloseMinimizeTrading.sol
> +    // 7. Reset approval for safety reason
Should return remaining LPs back to msg.sender (Worker).

2021-07-02 08:49 UTC, spicysquid168 requested changes

2021-07-02 08:49 UTC, spicysquid168 commented on contracts/6/protocol/strategies/waultswap-restricted/WaultSwapRestrictedStrategyPartialCloseMinimizeTrading.sol
> +      abi.decode(data, (uint256, uint256, uint256));
add require(toRepaidBaseTokenDebt <= debt)

2021-07-09 04:34 UTC, spicysquid168 approved these changes

2021-07-09 04:42 UTC, sundayalpaca approved these changes

2021-07-09 04:43 UTC, ricardo-alpaca approved these changes

2021-07-09 05:11 UTC, merged