[main][fix] strategy partial close liquidate
alpaca-finance/bsc-alpaca-contract pull request #77
Opened 2021-07-01 05:24 UTC by jakeal-papaca

## Description
 - add event to PancakeswapV2RestrictedStrategyPartialCloseLiquidate and WaultSwapRestrictedStrategyPartialCloseLiquidate contract

## Changelogs
 - PancakeswapV2RestrictedStrategyPartialCloseLiquidate, WaultSwapRestrictedStrategyPartialCloseLiquidate contract
 - unit test

2021-07-01 09:25 UTC, spicysquid168 requested changes

2021-07-01 09:25 UTC, spicysquid168 commented on contracts/6/protocol/strategies/waultswap-restricted/WaultSwapRestrictedStrategyPartialCloseLiquidate.sol
> +    (uint256 lpTokenToLiquidate, uint256 toRepaidBaseTokenDebt, uint256 minBaseToken) =
What is the use of `toRepaidBaseTokenDebt` except emit event?

2021-07-01 09:25 UTC, spicysquid168 commented on test/PancakeswapV2_Restricted_StrategyPartialCloseLiquidate.test.ts
> +      )).to.emit(strat, 'PancakeswapV2RestrictedStrategyPartialCloseLiquidateEvent')
expect args too

2021-07-01 09:25 UTC, spicysquid168 commented on test/WaultSwap_Restricted_StrategyPartialCloseLiquidate.test.ts
> +      )).to.emit(strat, 'WaultSwapRestrictedStrategyPartialCloseLiquidateEvent')
expect args from event too

2021-07-01 10:20 UTC, jakeal-papaca commented on contracts/6/protocol/strategies/waultswap-restricted/WaultSwapRestrictedStrategyPartialCloseLiquidate.sol
> +    (uint256 lpTokenToLiquidate, uint256 toRepaidBaseTokenDebt, uint256 minBaseToken) =
only emit event

2021-07-02 08:15 UTC, spicysquid168 requested changes

2021-07-02 08:15 UTC, spicysquid168 commented on contracts/6/protocol/strategies/pancakeswapV2-restricted/PancakeswapV2RestrictedStrategyPartialCloseLiquidate.sol
> +      abi.decode(data, (uint256, uint256, uint256));
add require(toRepaidBaseTokenDebt <= debt)

2021-07-08 10:26 UTC, spicysquid168 submitted a review, later dismissed

2021-07-09 04:41 UTC, spicysquid168 submitted a review, later dismissed

2021-07-09 04:42 UTC, sundayalpaca submitted a review, later dismissed

2021-07-09 05:30 UTC, spicysquid168 approved these changes

2021-07-09 05:31 UTC, sundayalpaca approved these changes

2021-07-09 05:31 UTC, almost-llamas approved these changes

2021-07-09 05:59 UTC, merged