[main][feat] change liquidator bot
alpaca-finance/bsc-alpaca-contract pull request #80
Opened 2021-07-07 07:42 UTC by abc-alpaca

## Description

## Why?

2021-07-07 07:47 UTC, almost-llamas commented on contracts/6/protocol/ConfigurableInterestVaultConfig.sol
> +  /// @param _buyBack The reward for buybackAnd Burn Address
`the address where buy back and burn portion transferred to`

2021-07-07 07:49 UTC, almost-llamas commented on contracts/6/protocol/ConfigurableInterestVaultConfig.sol
> +  /// @param _buyBackBps The reward for buyback and burn after successfully killing a position.
`The portion of reward for buy back and burn after successfully killing a position.`

2021-07-07 07:52 UTC, almost-llamas commented on contracts/6/protocol/ConfigurableInterestVaultConfig.sol
> +  // The address of buyback
`The address where buyback and burn portion will be transferred to.`

2021-07-07 07:52 UTC, almost-llamas commented on contracts/6/protocol/ConfigurableInterestVaultConfig.sol
> +  // The reward for buyback and burn after successfully killing a position.
`The portion of reward for buyback and burn after successfully killing a position.`

2021-07-07 10:27 UTC, almost-llamas requested changes
Please also adjust the deployment script as the constructor of the contract has been changed.

2021-07-07 11:32 UTC, spicysquid168 requested changes

2021-07-07 11:32 UTC, spicysquid168 commented on contracts/6/protocol/ConfigurableInterestVaultConfig.sol
> +  uint256 public override getBuybackBps;
`getKillTreasuryBps` would be better reflect the real meaning as we will use this part of fee to reserve for bad debt. Then if no bad debt happened, will be used for buyback later.

2021-07-07 11:32 UTC, spicysquid168 commented on contracts/6/protocol/ConfigurableInterestVaultConfig.sol
> +  address public buyback;
Please use `treasuryAccount` instead

2021-07-07 11:32 UTC, spicysquid168 commented on contracts/6/protocol/ConfigurableInterestVaultConfig.sol
> +    return buyback;
Please also handle the case where `treasuryAccount` haven't been set yet (if `treasuryAccount == address(0)`), then return Deployer address first (0xC44f82b07Ab3E691F826951a6E335E1bC1bB0B51)

2021-07-07 11:32 UTC, spicysquid168 commented on contracts/6/protocol/ConfigurableInterestVaultConfig.sol
> +    return buyback;
This case can happen as we will upgrade the implementation contract of VaultConfig, then after upgrade the `treasuryAccount` will has `address(0)` value.

2021-07-07 11:32 UTC, spicysquid168 commented on contracts/6/protocol/ConfigurableInterestVaultConfig.sol
>      require(_killBps <= maxKillBps, "ConfigurableInterestVaultConfig::setParams:: kill bps exceeded max kill bps");
This require should be updated to `require(_killBps.add(_getKillTresauryBps) <= maxKillBps, "...")` as `_getKillTreasuryBps` is a part of total `killBps`

2021-07-07 11:32 UTC, spicysquid168 commented on contracts/6/protocol/SimpleVaultConfig.sol
> +  uint256 public override getBuybackBps;
please apply the same comments as `ConfigurableInterestVaultConfig` above

2021-07-07 11:36 UTC, spicysquid168 requested changes

2021-07-07 11:36 UTC, spicysquid168 commented on contracts/6/protocol/Vault.sol
> +    uint256 buybackBurnPrize = back.mul(config.getBuybackBps()).div(10000);
should rename to `tresauryFees`

2021-07-07 11:40 UTC, spicysquid168 requested changes

2021-07-07 11:40 UTC, spicysquid168 commented on test/CakeMaxiWorker.test.ts
> +  const BUYBACK_OVERFLOW_BPS = '500' //5% Buyback & Burn (10% prize + 5% BB causes bad debt)
Better simulate by swap a huge FTOKEN -> BTOKEN than force BUYBACK_OVERFLOW

2021-07-09 05:06 UTC, abc-alpaca commented on contracts/6/protocol/ConfigurableInterestVaultConfig.sol
>      require(_killBps <= maxKillBps, "ConfigurableInterestVaultConfig::setParams:: kill bps exceeded max kill bps");
I using + instead of add

2021-07-09 06:04 UTC, spicysquid168 requested changes

2021-07-09 06:04 UTC, spicysquid168 commented on contracts/6/protocol/Vault.sol
> +      SafeToken.safeTransfer(token, config.getWNativeRelayerAddr(), amount);
please keep the above lines the same. `config.getWNativeRelayer()`

2021-07-09 06:04 UTC, spicysquid168 commented on contracts/6/protocol/interfaces/IVaultConfig.sol
> +  function getWNativeRelayerAddr() external view returns (address);
Keep the interface here the same

2021-07-09 06:04 UTC, spicysquid168 commented on contracts/6/protocol/SimpleVaultConfig.sol
> +  address public override getWNativeRelayerAddr;
should be `getWNativeRelayer`

2021-07-12 03:56 UTC, almost-llamas commented on contracts/6/protocol/ConfigurableInterestVaultConfig.sol
>    // The address where buyback and burn portion will be transferred to.
```
// address of treasury account

2021-07-12 03:57 UTC, almost-llamas commented on contracts/6/protocol/ConfigurableInterestVaultConfig.sol
>    // The portion of reward for buyback and burn after successfully killing a position.
```
  // The portion of reward that will be transferred to treasury account  after successfully killing a position.

2021-07-12 03:58 UTC, almost-llamas commented on contracts/6/protocol/ConfigurableInterestVaultConfig.sol
> +  /// @param _treasury The address where buyback and burn portion will be transferred to.
revise the comment, referring to previous comments

2021-07-12 03:58 UTC, almost-llamas commented on contracts/6/protocol/SimpleVaultConfig.sol
> +  address public treasury;
revise the comment, referring to previous comments

2021-07-12 03:58 UTC, almost-llamas commented on contracts/6/protocol/interfaces/IVaultConfig.sol
> +  function getTreasuryAddr() external view returns (address);
revise the comment, referring to previous comments

2021-07-12 04:22 UTC, almost-llamas submitted a review, later dismissed

2021-07-12 04:33 UTC, spicysquid168 requested changes

2021-07-12 04:33 UTC, spicysquid168 commented on deploy/008_deploy_configurable_interest_vault_config.ts
> +  const BUYBACK_BPS = '250';
TREASURY_KILL_BPS?

2021-07-12 04:33 UTC, spicysquid168 commented on deploy/008_deploy_configurable_interest_vault_config.ts
> +  const BUYBACK_ADDR = '';
TREASURY_ADDR?

2021-07-12 04:33 UTC, spicysquid168 commented on contracts/6/protocol/ConfigurableInterestVaultConfig.sol
> +    return treasury == address(0) ? 0xC44f82b07Ab3E691F826951a6E335E1bC1bB0B51 : treasury;
Please add test-case that cover this line too.

2021-07-12 08:47 UTC, almost-llamas approved these changes

2021-07-12 08:51 UTC, spicysquid168 approved these changes

2021-07-12 08:52 UTC, merged